import * as T from 'three';import {GLTFLoader} from './vendor/GLTFLoader.js';import {clone} from './vendor/SkeletonUtils.js';
const wp=o=>o.getWorldPosition(new T.Vector3());
function aimBone(bone,from,to){const origin=wp(bone),a=from.clone().sub(origin).normalize(),b=to.clone().sub(origin).normalize(),q=new T.Quaternion().setFromUnitVectors(a,b).multiply(bone.getWorldQuaternion(new T.Quaternion()));bone.quaternion.copy(bone.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(q));bone.updateWorldMatrix(false,true);}
function arm(model,side,target){const upper=model.getObjectByName('UpperArm'+side),lower=model.getObjectByName('LowerArm'+side),hand=model.getObjectByName('Middle1'+side);const p=wp(upper),el=wp(lower),h=wp(hand),l1=p.distanceTo(el),l2=el.distanceTo(h),d=target.clone().sub(p),dist=Math.min(d.length(),(l1+l2)*.96);d.normalize();const along=(l1*l1-l2*l2+dist*dist)/(2*dist),height=Math.sqrt(Math.max(.001,l1*l1-along*along));const out=new T.Vector3(side==='L'?.8:-.8,-1,0).transformDirection(model.matrixWorld);out.addScaledVector(d,-out.dot(d)).normalize();const elbow=p.clone().addScaledVector(d,along).addScaledVector(out,height);aimBone(upper,el,elbow);aimBone(lower,wp(hand),p.clone().addScaledVector(d,dist));}
export async function actorFactory(scene){const g=await new GLTFLoader().loadAsync('./assets/soldier.gltf'),base=g.scene;const hide=['GrenadeLauncher','Knife_1','Knife_2','Pistol','Revolver','Revolver_Small','RocketLauncher','ShortCannon','Shotgun','Shovel','SMG','Sniper','Sniper_2'];base.traverse(o=>{if(hide.includes(o.name))o.visible=false;if(o.isMesh){o.material=o.material.clone();if(o.material.name==='Character_Main')o.material.color.set('#148edc');if(o.material.name==='Pants')o.material.color.set('#27537a');o.material.roughness=.8;}});base.updateMatrixWorld(true);const gun=base.getObjectByName('AK');let tip=new T.Vector3(),rear=new T.Vector3(),z=-Infinity,minZ=Infinity;gun.traverse(o=>{if(o.isMesh){const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){const p=new T.Vector3().fromBufferAttribute(a,i);o.localToWorld(p);if(p.z>z){z=p.z;tip.copy(p)}if(p.z<minZ){minZ=p.z;rear.copy(p)}}}});gun.worldToLocal(tip);gun.worldToLocal(rear);const forward=tip.clone().sub(rear).normalize();const restGunQ=gun.getWorldQuaternion(new T.Quaternion());
const cv=document.createElement('canvas');cv.width=cv.height=64;const ctx=cv.getContext('2d'),gr=ctx.createRadialGradient(32,32,2,32,32,31);gr.addColorStop(0,'#11232b66');gr.addColorStop(.55,'#11232b33');gr.addColorStop(1,'#11232b00');ctx.fillStyle=gr;ctx.fillRect(0,0,64,64);const tex=new T.CanvasTexture(cv),shadowMat=new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false});
function make(x,z,side='blue',phase=0){const model=clone(base);model.scale.setScalar(.65);model.rotation.y=side==='blue'?Math.PI:0;model.position.set(x,0,z);if(side!=='blue')model.traverse(o=>{if(o.isMesh&&o.material.name==='Character_Main'){o.material=o.material.clone();o.material.color.set(side==='shield'?'#8b6cc0':side==='shooter'?'#dc9250':'#c35848')}});scene.add(model);const mixer=new T.AnimationMixer(model),clip=g.animations.find(c=>c.name==='Run_Shoot'),action=mixer.clipAction(clip);action.play();action.time=phase*clip.duration;const gun=model.getObjectByName('AK'),socket=new T.Object3D();socket.position.copy(tip);gun.add(socket);const flash=new T.Mesh(new T.SphereGeometry(.095,5,3),new T.MeshBasicMaterial({color:0xffefb3}));socket.add(flash);flash.visible=false;const shadow=new T.Mesh(new T.PlaneGeometry(1.2,.9),shadowMat);shadow.rotation.x=-Math.PI/2;shadow.position.set(x,.05,z);scene.add(shadow);const feet=[];model.traverse(o=>{if(o.isSkinnedMesh){const p=o.geometry.attributes.position;let ids=[];for(let i=0;i<p.count;i++)ids.push(i);ids.sort((a,b)=>p.getY(a)-p.getY(b));feet.push({mesh:o,ids:ids.slice(0,36)})}});
const gaitTracks=clip.tracks.filter(t=>/^(Root|FootL|FootR|UpperLegL|UpperLegR|LowerLegL|LowerLegR|Body_1|Hips|PoleTargetL|PoleTargetR)\./.test(t.name)).map(t=>({node:model.getObjectByName(t.name.split('.')[0]),prop:t.name.split('.')[1],interp:t.createInterpolant()}));const a={gaitTime:phase*clip.duration,celebrating:false,model,mixer,action,socket,flash,shadow,flashAge:0,phase,side,feet,stance:0,stepTime:0,shotTime:phase*.36,
 update(dt,walking=true,fire=false){const old=action.time;action.timeScale=walking?1.05:0;mixer.update(dt);if(walking&&!a.celebrating){a.gaitTime=(a.gaitTime+dt*1.24)%clip.duration;for(const t of gaitTracks)if(t.node)t.node[t.prop].fromArray(t.interp.evaluate(a.gaitTime));}model.position.y=0;model.updateMatrixWorld(true);const q=model.getWorldQuaternion(new T.Quaternion()).multiply(restGunQ);q.premultiply(new T.Quaternion().setFromUnitVectors(forward.clone().applyQuaternion(q),new T.Vector3(0,0,1).transformDirection(model.matrixWorld)));const target=model.localToWorld(new T.Vector3(-.22,1.38,.43));arm(model,'R',target);gun.quaternion.copy(gun.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(q));gun.updateWorldMatrix(false,true);const grip=socket.getWorldPosition(new T.Vector3());grip.add(new T.Vector3(0,-.08,-.28).transformDirection(model.matrixWorld).multiplyScalar(.31));arm(model,'L',grip);model.updateMatrixWorld(true);
 let bottom=Infinity;for(const f of feet){f.mesh.skeleton.update();for(const i of f.ids){const v=new T.Vector3().fromBufferAttribute(f.mesh.geometry.attributes.position,i);f.mesh.applyBoneTransform(i,v);f.mesh.localToWorld(v);bottom=Math.min(bottom,v.y)}}if(Number.isFinite(bottom)){model.position.y+=.04-bottom;}model.updateMatrixWorld(true);shadow.position.set(model.position.x,.05,model.position.z);flashAge();function flashAge(){a.flashAge-=dt;a.flash.visible=a.flashAge>0}const now=action.time/clip.duration;let emit=false;if(fire&&walking)for(const f of[.18,.68])if((old/clip.duration<f&&now>=f)||(now<old/clip.duration&&(f>old/clip.duration||f<=now)))emit=true;return emit;},
 celebrate(){a.celebrating=true;mixer.stopAllAction();mixer.clipAction(g.animations.find(c=>c.name==='Yes')).reset().play();},muzzle(){this.flashAge=.045;flash.visible=true;return socket.getWorldPosition(new T.Vector3())},remove(){scene.remove(model,shadow)},dispose(){scene.remove(model,shadow)}};return a;}
return{make,clips:g.animations.map(a=>a.name),tip:tip.toArray(),source:base};}





