'use strict';
const MACHINES=[
{id:'volt',name:'ヴォルト',tag:'連鎖電撃',cost:0,color:'#8ff9e8',desc:'狙った敵から隣の敵へ電撃が連鎖。密集した大群をまとめて倒す。',evo:['連鎖数 +2','放電速度 UP','連鎖ダメージ UP']},
{id:'lance',name:'ランサー',tag:'収束レーザー',cost:100,color:'#a6bdff',desc:'同じ方向を狙い続けるとレーザーが太く強くなる。移動すると出力が下がる。',evo:['照射幅 UP','チャージ速度 UP','最大出力 UP']},
{id:'swarm',name:'スウォーム',tag:'追尾ミサイル',cost:240,color:'#ffd087',desc:'敵を追うミサイルを一斉発射。自分は回避に集中し、側面の敵まで追い詰める。',evo:['同時発射 +2','発射間隔 短縮','爆発範囲 UP']}
];
const ARSENAL_KEY='breach-arsenal-v1';let arsenalSaved=true;
function loadArsenal(){try{let d=JSON.parse(localStorage.getItem(ARSENAL_KEY)||'{}')||{};return {credits:Number.isFinite(d.credits)?Math.max(0,Math.floor(d.credits)):0,owned:['volt',...['lance','swarm'].filter(id=>d.owned?.includes(id))],selected:MACHINES.some(m=>m.id===d.selected)&&d.owned?.includes(d.selected)?d.selected:'volt'};}catch{return {credits:0,owned:['volt'],selected:'volt'}}}
let arsenal=loadArsenal(),chosenMachine=arsenal.selected,runMachine=MACHINES[0],modules=[0,0,0],specialClock=0,beamCharge=0,lastAim=0,arcs=[],missiles=[],beamFlash=0,earnedThisRun=false,trialRun=false;
function saveArsenal(){try{localStorage.setItem(ARSENAL_KEY,JSON.stringify(arsenal));arsenalSaved=true}catch{arsenalSaved=false}}
function nextMachine(){return MACHINES.find(m=>!arsenal.owned.includes(m.id))}
function goalText(){let next=nextMachine();return next?'次の解放：'+next.name+' / あと '+Math.max(0,next.cost-arsenal.credits)+' 素材':'全機体解放！ 武装の組み合わせを試そう。'}
function renderHangar(){const m=MACHINES.find(m=>m.id===chosenMachine);$('hangarChoice').textContent=m.name+' / '+m.tag+(arsenal.owned.includes(m.id)?'':'〈試乗〉');$('hangarGoal').textContent=goalText();$('materialCount').textContent=arsenal.credits+' 素材';$('machineCards').innerHTML=MACHINES.map(m=>{const owned=arsenal.owned.includes(m.id),selected=chosenMachine===m.id;return '<article class="machine-card '+(selected?'equipped':'')+'" style="--machine:'+m.color+'"><div class="machine-symbol">'+(m.id==='volt'?'ϟ':m.id==='lance'?'Ⅱ':'✦')+'</div><div><small>'+m.tag+'</small><h3>'+m.name+'</h3><p>'+m.desc+'</p><p class="evo-description">進化：'+m.evo.join(' / ')+'</p><div class="machine-actions">'+(owned?'<button data-equip="'+m.id+'" '+(selected?'disabled':'')+'>'+(selected?'選択中':'この機体で出撃')+'</button>':'<button data-trial="'+m.id+'">1戦試乗する</button><button data-unlock="'+m.id+'" '+(arsenal.credits<m.cost?'disabled':'')+'>'+m.cost+' 素材で解放</button>')+'</div></div></article>'}).join('');$('arsenalNotice').textContent=arsenalSaved?'素材は勝敗にかかわらず戦闘結果で獲得。試乗は何度でもできます。':'この環境では保存できません。今回の記録は画面を閉じると失われます。';}
function openHangar(){if(state==='playing')pause();renderHangar();$('hangar').classList.remove('hidden')}
$('hangarChoice').onclick=openHangar;$('resultHangar').onclick=openHangar;$('closeHangar').onclick=()=>$('hangar').classList.add('hidden');
$('machineCards').onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const id=b.dataset.equip||b.dataset.trial||b.dataset.unlock,m=MACHINES.find(m=>m.id===id);if(!m)return;if(b.dataset.unlock){if(arsenal.owned.includes(id)||arsenal.credits<m.cost)return;arsenal.credits-=m.cost;arsenal.owned.push(id);arsenal.selected=id;chosenMachine=id;saveArsenal();toast(m.name+' 解放！',m.color);battleAudio.effect('upgrade');}else{chosenMachine=id;if(arsenal.owned.includes(id)){arsenal.selected=id;saveArsenal();}$('hangar').classList.add('hidden');}renderHangar();};
const arsenalStart=start,arsenalFinish=finish,arsenalEquip=equip,arsenalUpdate=update,arsenalDraw=draw,arsenalObject=drawObject,arsenalHome=home;
start=function(n=level){runMachine=MACHINES.find(m=>m.id===chosenMachine)||MACHINES[0];trialRun=!arsenal.owned.includes(runMachine.id);modules=[0,0,0];specialClock=.7;beamCharge=0;lastAim=0;arcs=[];missiles=[];beamFlash=0;earnedThisRun=false;$('hangar').classList.add('hidden');arsenalStart(n);toast(runMachine.name+' / '+runMachine.tag+(trialRun?' 試乗':''),runMachine.color);};
home=function(){arsenalHome();$('hangar').classList.add('hidden');renderHangar();};$('home').onclick=home;$('pauseHome').onclick=home;
finish=function(win){if(state!=='playing')return;arsenalFinish(win);if(earnedThisRun)return;earnedThisRun=true;const earned=win?30+Math.min(30,Math.floor(kills/5)):Math.min(25,Math.floor(kills/5));arsenal.credits+=earned;saveArsenal();$('researchResult').textContent='開発素材 +'+earned+' / 所持 '+arsenal.credits+'　'+goalText()+(arsenalSaved?'':'（保存できません）');if(trialRun){chosenMachine=arsenal.selected;$('researchResult').textContent+='　試乗終了。格納庫から再試乗できます。';}renderHangar();};
equip=function(kind){arsenalEquip(kind);const i=['wide','pierce','blast'].indexOf(kind);if(i>=0){modules[i]++;toast(runMachine.name+'：'+runMachine.evo[i],runMachine.color);}};
function liveTargets(){return objects.filter(o=>!o.dead&&['enemy','boss'].includes(o.type)&&o.z-distance>3&&o.z-distance<(o.type==='boss'?36:(expeditionActive()?34:54))).sort((a,b)=>Math.abs(a.x-px)-Math.abs(b.x-px)||a.z-b.z)}
update=function(dt){arsenalUpdate(dt);if(state!=='playing')return;specialClock-=dt;beamFlash=Math.max(0,beamFlash-dt);for(const arc of arcs)arc.life-=dt;arcs=arcs.filter(a=>a.life>0);const ts=liveTargets(),power=12+firepower()*.38;
if(runMachine.id==='volt'&&specialClock<=0&&ts.some(t=>Math.abs(t.x-px)<.28)){specialClock=1.1/(1+modules[1]*.3);recordMuzzle(px,'volt');let source={x:px,z:distance+2},pool=ts.slice(),count=3+modules[0]*2;for(let i=0;i<count&&pool.length&&state==='playing';i++){pool.sort((a,b)=>(Math.abs(a.x-source.x)*35+Math.abs(a.z-source.z))-(Math.abs(b.x-source.x)*35+Math.abs(b.z-source.z)));let t=i===0?pool.find(t=>Math.abs(t.x-px)<.28):pool[0];if(!t||i>0&&(Math.abs(t.x-source.x)>.8||Math.abs(t.z-source.z)>15))break;pool.splice(pool.indexOf(t),1);arcs.push({a:{x:source.x,z:source.z},b:{x:t.x,z:t.z},life:.18});hitEnemy(t,power*(1+modules[2]*.4),'volt');source=t;}battleAudio.effect('hit');}
if(runMachine.id==='lance'){const movement=Math.abs(px-lastAim);beamCharge=clamp(beamCharge+(movement/Math.max(dt,.001)>.36?-dt*2.8:dt*(.48+modules[1]*.22)),0,1);lastAim=px;if(specialClock<=0){specialClock=.16;beamFlash=.10;recordMuzzle(px,'lance');const width=.07+modules[0]*.045+beamCharge*.08;for(const t of ts){if(state!=='playing')break;if(Math.abs(t.x-px)<width+(t.type==='boss'?.25:.10))hitEnemy(t,power*.22*(.5+beamCharge*(2+modules[2]*.7)),'lance');}}}
if(runMachine.id==='swarm'&&specialClock<=0&&ts.length){specialClock=1.5/(1+modules[1]*.3);for(let i=0;i<3+modules[0]*2;i++)missiles.push({...missileOrigin(px+(i%2?-.10:.10)),target:ts[i%ts.length],power:power*.65,life:3});}
for(const m of missiles){if(state!=='playing')break;m.life-=dt;if(m.target.dead)m.target=liveTargets()[0];if(!m.target){m.life=0;continue;}const dx=m.target.x-m.x,dz=m.target.z-m.z;m.x+=dx*Math.min(1,dt*6);m.z+=Math.sign(dz)*Math.min(Math.abs(dz),dt*46);if(Math.abs(dz)<2&&Math.abs(dx)<.16){m.life=0;const t=m.target;hitEnemy(t,m.power,'swarm');rings.push({x:t.x,z:t.z-distance,life:.25,max:.25,color:runMachine.color});if(modules[2])for(const other of ts){if(state!=='playing')break;if(other!==t&&!other.dead&&Math.abs(other.x-t.x)<.2+modules[2]*.15&&Math.abs(other.z-t.z)<3)hitEnemy(other,m.power*.5,'swarm');}}}missiles=missiles.filter(m=>m.life>0).slice(-30);
$('weaponType').textContent=runMachine.name;$('weaponName').textContent=runMachine.tag+' '+modules.map(n=>'Ⅰ'.repeat(n)).filter(Boolean).join('・');if(runMachine.id==='lance')$('combo').textContent='出力 '+Math.round(beamCharge*100)+'%';};
drawObject=function(o){if(o.type!=='pickup'||o.kind==='reinforce')return arsenalObject(o);const rel=o.z-distance;if(rel>110||rel<-.5)return;const p=project(o.x,rel),s=p.s,w=W*.39*s,i=['wide','pierce','blast'].indexOf(o.kind);round(p.x-w/2,p.y-49*s,w,42*s,5*s,'#102c43',runMachine.color);txt(runMachine.evo[i],p.x,p.y-28*s,Math.max(11,14*s),runMachine.color);txt(['＋ ワイド弾','＋ 貫通弾','＋ 榴弾支援'][i],p.x,p.y+6*s,Math.max(10,11*s),'#d2e7f0');};
draw=function(dt){arsenalDraw(dt);if(!['playing','paused'].includes(state))return;ctx.save();ctx.globalCompositeOperation='lighter';for(const a of arcs){let p=project(a.a.x,a.a.z-distance),q=project(a.b.x,a.b.z-distance);if(a.a.z-distance<3){const m=weaponOrigin(a.a.x);p={x:m.x,y:m.y+14*p.s,s:p.s};}ctx.globalAlpha=clamp(a.life/.18,0,1);ctx.strokeStyle=runMachine.color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y-14*p.s);for(let j=1;j<5;j++)ctx.lineTo(p.x+(q.x-p.x)*j/5+(j%2?7:-7),p.y+(q.y-p.y)*j/5-14*p.s);ctx.lineTo(q.x,q.y-15*q.s);ctx.stroke();}ctx.globalAlpha=1;if(runMachine.id==='lance'&&beamFlash>0){const origin=weaponOrigin(),p={x:origin.x,y:origin.y+14,s:1},q=project(px,55);ctx.strokeStyle='#829bff66';ctx.lineWidth=5+beamCharge*15+modules[0]*4;ctx.beginPath();ctx.moveTo(p.x,p.y-14*p.s);ctx.lineTo(q.x,q.y-8);ctx.stroke();ctx.strokeStyle='#e4eaff';ctx.lineWidth=2+beamCharge*3;ctx.stroke();}for(const m of missiles){let p=project(m.x,m.z-distance),q=project(m.x,Math.max(m.bornZ??distance+2,m.z-1.3)-distance);ctx.strokeStyle='#ffbd68';ctx.lineWidth=3*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y-14*p.s);ctx.lineTo(q.x,q.y-14*q.s);ctx.stroke();}ctx.restore();};
renderHangar();
