'use strict';
// Original procedural score and layered effects. No external audio files.
class BattleAudio {
 constructor(){this.ctx=null;this.enabled=false;this.musicEnabled=true;this.step=0;this.next=0;this.limits={};this.playing=false;}
 init(){if(this.ctx)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.ctx=new A();const c=this.ctx;this.master=c.createGain();this.master.gain.value=.58;const limiter=c.createDynamicsCompressor();limiter.threshold.value=-15;limiter.knee.value=12;limiter.ratio.value=8;this.fx=c.createGain();this.fx.gain.value=.65;this.music=c.createGain();this.music.gain.value=.24;this.fx.connect(this.master);this.music.connect(this.master);this.master.connect(limiter);limiter.connect(c.destination);this.noise=c.createBuffer(1,c.sampleRate*.5,c.sampleRate);let data=this.noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;}
 enable(on){this.enabled=on;if(on){try{this.init();this.ctx?.resume().catch(()=>{});}catch{this.enabled=false;}}if(this.ctx)this.master.gain.setTargetAtTime(this.enabled?.58:0,this.ctx.currentTime,.02);return this.enabled;}
 tone(freq,duration,volume,type='sine',when=0,end=freq,bus=this.fx){if(!this.ctx||!this.enabled)return;const c=this.ctx,t=when||c.currentTime;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,volume),t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(bus);o.start(t);o.stop(t+duration+.01);o.onended=()=>{o.disconnect();g.disconnect()};}
 hiss(duration,volume,cutoff=2000,when=0,bus=this.fx){if(!this.ctx||!this.enabled)return;const c=this.ctx,t=when||c.currentTime,o=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();o.buffer=this.noise;f.type='lowpass';f.frequency.value=cutoff;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(f);f.connect(g);g.connect(bus);o.start(t);o.stop(t+duration);o.onended=()=>{o.disconnect();f.disconnect();g.disconnect()};}
 effect(kind,intensity=0){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime;if(t<(this.limits[kind]||0))return;this.limits[kind]=t+({shot:.055,hit:.07,kill:.06,boom:.13}[kind]||.06);if(kind==='shot'){this.hiss(.028,.13,2300+intensity*300);this.tone(140+intensity*12,.045,.13,'triangle',0,55);}
 else if(kind==='hit'){this.hiss(.025,.08,4100);this.tone(950,.025,.045,'sine',0,360);}
 else if(kind==='kill'){this.hiss(.065,.13,1800);this.tone(220+Math.min(intensity,12)*17,.09,.11,'triangle',0,70);}
 else if(kind==='boom'){this.hiss(.38,.30,700);this.tone(115,.28,.37,'sine',0,28);}
 else if(kind==='hurt'){this.hiss(.15,.18,1300);this.tone(150,.22,.28,'sawtooth',0,38);}
 else if(kind==='warn'){this.tone(390,.12,.13,'square');this.tone(310,.14,.11,'square',t+.17);}
 else {const notes=kind==='lose'?[330,277,220]:kind==='rush'?[220,330,440,660,880]:kind==='win'?[392,494,587,784]:[440,554,659];notes.forEach((f,i)=>this.tone(f,.20,kind==='rush'?.18:.12,'triangle',t+i*.075));}}
 tick(playing,rushing){if(!this.ctx||!this.enabled)return;const c=this.ctx;const active=playing&&this.musicEnabled;if(active!==this.playing){this.music.gain.setTargetAtTime(active?.24:0,c.currentTime,.07);this.playing=active;this.next=c.currentTime+.02;}if(!active)return;const beat=60/116/2;let guard=0;while(this.next<c.currentTime+.08&&guard++<3){const t=Math.max(this.next,c.currentTime),i=this.step%16;const notes=[110,110,130.81,110,164.81,110,146.83,130.81];this.tone(notes[this.step%8],beat*.78,.28,'triangle',t,notes[this.step%8],this.music);if(i%4===0)this.tone(125,.15,.5,'sine',t,36,this.music);if(i%4===2)this.hiss(.07,.18,1700,t,this.music);this.hiss(.025,.07,6500,t,this.music);if(rushing){this.tone(notes[(this.step+2)%8]*4,.10,.095,'square',t,notes[(this.step+2)%8]*4,this.music);this.hiss(.022,.065,7500,t+beat*.5,this.music);}this.step++;this.next=t+beat;}}
}
const battleAudio=new BattleAudio();
