'use strict';
// One atomic profile + run record. Legacy v13 saves are imported, never deleted.
function validEquipmentProfile(a){if(!a)return false;return (!a.relics||Object.entries(a.relics).every(([id,r])=>['prism','guardian'].includes(id)&&r&&Number.isFinite(r.operation)&&Number.isFinite(r.score)))&&(!a.installed||Array.isArray(a.installed)&&a.installed.every(id=>['prism','guardian'].includes(id)&&a.relics?.[id]));}
const CHECKPOINT_KEY='breach-save-v2',CHECKPOINT_BACKUP='breach-save-v2-backup';
const checkpointOwner=crypto.randomUUID();
let checkpointData=null,checkpointRunId=null,checkpointOwned=false,checkpointRestoring=false,checkpointFinishing=false,checkpointFrozen=false,checkpointClock=0,checkpointFailed=false,checkpointPendingResult=null;
const cloneCheckpoint=v=>JSON.parse(JSON.stringify(v));
function checkpointHash(text){let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return(h>>>0).toString(16);}
function checkpointPack(data){return JSON.stringify({version:2,data,checksum:checkpointHash(JSON.stringify(data))});}
function checkpointProfile(){return cloneCheckpoint({campaign,arsenal,lessonSeen});}
function validCheckpointProfile(p){return validEquipmentProfile(p?.arsenal)&&p&&validTacticsProfile(p.campaign||{})&&p.campaign&&p.campaign.records&&typeof p.campaign.records==='object'&&!Array.isArray(p.campaign.records)&&Object.entries(p.campaign.records).every(([n,r])=>/^(10|[1-9])$/.test(n)&&r&&Number.isFinite(r.score)&&r.score>=0&&Number.isInteger(r.clears)&&r.clears>0&&Number.isFinite(r.time)&&r.time>=0&&Array.isArray(r.stars)&&r.stars.length===3&&r.stars.every(v=>typeof v==='boolean'))&&p.arsenal&&Number.isFinite(p.arsenal.credits)&&p.arsenal.credits>=0&&Array.isArray(p.arsenal.owned)&&p.arsenal.owned.includes('volt')&&p.arsenal.owned.every(id=>MACHINES.some(m=>m.id===id))&&p.arsenal.owned.includes(p.arsenal.selected)&&typeof p.lessonSeen==='boolean';}
function checkpointDecode(raw){if(!raw||raw.length>1500000)return null;try{const v=JSON.parse(raw);if(v.version>2)return{future:true};if(v.version!==2||!v.data||v.checksum!==checkpointHash(JSON.stringify(v.data))||!validCheckpointProfile(v.data.profile)||!Number.isInteger(v.data.revision)||v.data.revision<0)return null;return v.data;}catch{return null;}}
function checkpointRead(){try{return checkpointDecode(localStorage.getItem(CHECKPOINT_KEY));}catch{return null;}}
const recovery=document.createElement('section');recovery.id='recoveryMenu';recovery.className='overlay pausemenu hidden';recovery.setAttribute('aria-labelledby','recoveryTitle');
recovery.innerHTML='<span class="eyebrow">OPERATION SAVED</span><h2 id="recoveryTitle">つづきから遊ぶ</h2><p id="recoveryDetail"></p><p id="recoveryHelp">直前のチェックポイントから再開します。<small>突然アプリが閉じた場合は、最大約5秒前に戻ることがあります。</small></p><button class="primary" id="continueRun">つづきから</button><button class="secondary" id="restartSavedRun">この作戦を最初から</button><button class="textbutton" id="closeRecovery">タイトルへ</button>';$('app').append(recovery);
const saveMessage=document.createElement('p');saveMessage.id='checkpointMessage';saveMessage.setAttribute('role','status');saveMessage.hidden=true;$('app').append(saveMessage);
function checkpointMessage(text){saveMessage.textContent=text;saveMessage.hidden=!text;}
function checkpointWarning(){checkpointFailed=true;checkpointMessage('中断を保存できません。空き容量や保存設定を確認してください。前回保存した地点は保持しています。');}
function checkpointApplyProfile(p){campaign=cloneCheckpoint(p.campaign);arsenal=cloneCheckpoint(p.arsenal);lessonSeen=p.lessonSeen;chosenMachine=arsenal.selected;refreshCampaign();renderHangar();}
function checkpointWrite(data,{takeover=false}={}){if(checkpointFrozen)return false;if(checkpointPendingResult&&data.lastResult?.id!==checkpointRunId){data={...data,lastResult:checkpointPendingResult,run:data.run?.id===checkpointPendingResult.id?null:data.run};}try{const latest=checkpointRead();if(latest?.future){checkpointFrozen=true;checkpointMessage('新しい版の保存データがあります。保存を保護しています。新しい版で開いてください。');return false;}if(latest&&latest.revision>checkpointData.revision&&!takeover){checkpointOwned=false;checkpointMessage('別の画面で進行が更新されました。この画面を再読み込みして続けてください。');return false;}data.revision=Math.max(checkpointData.revision,latest?.revision||0)+1;const raw=checkpointPack(data);localStorage.setItem(CHECKPOINT_KEY,raw);checkpointData=data;checkpointPendingResult=null;checkpointMenu();try{localStorage.setItem(CHECKPOINT_BACKUP,raw)}catch{}checkpointFailed=false;checkpointMessage('');return true;}catch{checkpointWarning();return false;}}
function checkpointCapture(){const refs=new Map(objects.map((o,i)=>[o,i]));return{format:1,expedition:typeof expeditionRun==='undefined'?null:cloneCheckpoint(expeditionRun),values:{level,elapsed,distance,army,maxArmy,kills,px,targetX,shotClock,bossAnnounced,seed,wide,piercing,support,supportClock,volley,rush,rushCharge,rushCount,tier,bestCombo,impactChain,weapon,weaponLevel,combo,comboTime,score,lastDamage,bossTime,runBest,damageTaken,totalEnemies,specialClock,beamCharge,lastAim,trialRun,movedInRun},objects:cloneCheckpoint(objects),bullets:bullets.map(b=>({...b,hits:b.hits.map(o=>refs.get(o)).filter(i=>i!==undefined)})),missiles:missiles.map(m=>({...m,target:refs.get(m.target)??-1})),modules:modules.slice(),machine:runMachine.id,audio:{enabled:!muted,music:battleAudio.musicEnabled},lesson:lesson?{phase:lesson.phase,initial:lesson.initial,clock:lesson.clock,gateIndex:refs.get(lesson.gate)??-1,gate:cloneCheckpoint(lesson.gate)}:null};}
const checkpointNumbers=['level','elapsed','distance','army','maxArmy','kills','px','targetX','shotClock','seed','wide','piercing','support','supportClock','volley','rush','rushCharge','rushCount','tier','bestCombo','impactChain','weaponLevel','combo','comboTime','score','bossTime','runBest','damageTaken','totalEnemies','specialClock','beamCharge','lastAim'];
function checkpointFiniteTree(v,depth=0){if(depth>12)return false;if(typeof v==='number')return Number.isFinite(v)&&Math.abs(v)<1e12;if(typeof v==='string')return v.length<1000;if(v===null||typeof v==='boolean')return true;if(Array.isArray(v))return v.length<5000&&v.every(x=>checkpointFiniteTree(x,depth+1));if(v&&typeof v==='object')return Object.keys(v).length<100&&Object.values(v).every(x=>checkpointFiniteTree(x,depth+1));return false;}
function validCheckpointRun(r){if(!r||typeof r.id!=='string'||r.id.length>80||!r.snapshot)return false;const s=r.snapshot,v=s.values;if(!validExerciseSnapshot(s.expedition?.exercise,s.values?.level)||s.format!==1||(s.expedition&&((!Number.isInteger(s.expedition.mission)||s.expedition.mission<0||s.expedition.mission>10)||!Number.isInteger(s.expedition.relays)||s.expedition.relays<0||s.expedition.relays>3||!Number.isInteger(s.expedition.rescued)||s.expedition.rescued<0||s.expedition.rescued>3||typeof s.expedition.wardReady!=='boolean'))||!v||!checkpointFiniteTree(s)||!checkpointNumbers.every(k=>Number.isFinite(v[k]))||!Number.isInteger(v.level)||v.level<1||v.level>10||v.army<=0||v.distance<0||v.distance>180||v.elapsed<0||Math.abs(v.px)>.81||Math.abs(v.targetX)>.81||typeof v.bossAnnounced!=='boolean'||typeof v.trialRun!=='boolean'||typeof v.movedInRun!=='boolean'||typeof v.lastDamage!=='string'||!WEAPONS[v.weapon]||!MACHINES.some(m=>m.id===s.machine)||!Array.isArray(s.modules)||s.modules.length!==3||!s.modules.every(n=>Number.isInteger(n)&&n>=0&&n<=100)||!s.audio||typeof s.audio.enabled!=='boolean'||typeof s.audio.music!=='boolean')return false;
 if(!Array.isArray(s.objects)||s.objects.length>1000||!s.objects.every(o=>o&&['gate','pickup','enemy','boss','crate','obstacle','hazard'].includes(o.type)&&Number.isFinite(o.x)&&Number.isFinite(o.z)&&typeof o.dead==='boolean'&&(!['enemy','boss','crate'].includes(o.type)||Number.isFinite(o.hp)&&Number.isFinite(o.maxHp))&&(o.type!=='gate'||Number.isFinite(o.value)&&Number.isFinite(o.progress))&&(o.type!=='pickup'||['reinforce','wide','pierce','blast'].includes(o.kind))))return false;
 if(!Array.isArray(s.bullets)||s.bullets.length>2500||!s.bullets.every(b=>b&&['rapid','pierce','blast'].includes(b.kind)&&['x','z','damage','speed','remaining','vx'].every(k=>Number.isFinite(b[k]))&&Array.isArray(b.hits)&&b.hits.every(i=>Number.isInteger(i)&&i>=0&&i<s.objects.length)))return false;
 if(!Array.isArray(s.missiles)||s.missiles.length>100||!s.missiles.every(m=>m&&['x','z','power','life'].every(k=>Number.isFinite(m[k]))&&Number.isInteger(m.target)&&m.target>=-1&&m.target<s.objects.length))return false;
 if(s.lesson&&(!['aim','cross','join'].includes(s.lesson.phase)||!Number.isFinite(s.lesson.clock)||!Number.isFinite(s.lesson.initial)||!Number.isInteger(s.lesson.gateIndex)||(s.lesson.phase!=='join'&&s.objects[s.lesson.gateIndex]?.type!=='gate')||s.lesson.gate?.type!=='gate'))return false;return true;}
function saveCheckpoint(){if(checkpointRestoring||checkpointFinishing||!checkpointOwned||!['playing','paused'].includes(state)||!checkpointRunId)return false;return checkpointWrite({...checkpointData,profile:checkpointProfile(),run:{id:checkpointRunId,owner:checkpointOwner,savedAt:Date.now(),snapshot:checkpointCapture()}});}
function showRecovery(){const r=checkpointData.run;if(!r)return;const s=r.snapshot,m=MACHINES.find(m=>m.id===s.machine);$('recoveryDetail').textContent='作戦 '+String(s.values.level).padStart(2,'0')+' · 残り '+Math.ceil(180-s.values.distance)+'m · 部隊 '+s.values.army+'人\n'+m.name+(s.values.trialRun?'〈試乗中〉':'')+(s.lesson?' · 初回レッスンの途中':'');recovery.classList.remove('hidden');$('continueRun').focus();}
function checkpointMenu(){if(checkpointData.run){$('start').childNodes[0].textContent='つづきから ';}else $('start').childNodes[0].textContent='出撃する ';}
const checkpointStart=start,checkpointPause=pause,checkpointHome=home,checkpointUpdate=update,checkpointFinish=finish;
start=function(n=level,discard=false){if(checkpointData.run&&!discard){showRecovery();return;}checkpointRunId=crypto.randomUUID();checkpointOwned=true;checkpointFinishing=false;recovery.classList.add('hidden');checkpointStart(n);checkpointClock=0;saveCheckpoint();checkpointMenu();};
pause=function(){checkpointPause();if(state==='paused')saveCheckpoint();};
home=function(){saveCheckpoint();checkpointOwned=false;checkpointHome();checkpointMenu();};
update=function(dt){checkpointUpdate(dt);if(state==='playing'){checkpointClock+=dt;if(checkpointClock>=5){checkpointClock=0;saveCheckpoint();}}};
// Existing profile writers are routed through the same atomic record. Result writes
// are deferred until both campaign medals and arsenal materials have been computed.
persistCampaign=function(){if(checkpointFinishing||checkpointRestoring)return;storageOK=checkpointWrite({...checkpointData,profile:checkpointProfile()});};
saveArsenal=function(){if(checkpointFinishing||checkpointRestoring)return;arsenalSaved=checkpointWrite({...checkpointData,profile:checkpointProfile()});};
saveBest=function(){};
bestScore=function(n){return Number(campaign.records[n]?.score)||0;};
function restoreCheckpoint(){const latest=checkpointRead();if(latest?.future){checkpointMessage('新しい版で保存されています。新しい版で開いてください。');return;}if(latest&&latest.revision>checkpointData.revision){checkpointData=latest;checkpointApplyProfile(latest.profile);if(!latest.run){recovery.classList.add('hidden');checkpointMenu();checkpointMessage('この作戦はすでに終了しています。進行記録を読み込みました。');return;}}const r=checkpointData.run;if(!validCheckpointRun(r))return;checkpointPendingResult=null;checkpointApplyProfile(checkpointData.profile);const s=cloneCheckpoint(r.snapshot);checkpointRestoring=true;chosenMachine=s.machine;checkpointStart(s.values.level);
 ({level,elapsed,distance,army,maxArmy,kills,px,targetX,shotClock,bossAnnounced,seed,wide,piercing,support,supportClock,volley,rush,rushCharge,rushCount,tier,bestCombo,impactChain,weapon,weaponLevel,combo,comboTime,score,lastDamage,bossTime,runBest,damageTaken,totalEnemies,specialClock,beamCharge,lastAim,trialRun,movedInRun}=s.values);
 objects=s.objects;bullets=s.bullets.map(b=>({...b,hits:b.hits.map(i=>objects[i])}));missiles=s.missiles.map(m=>({...m,target:objects[m.target]||{dead:true}}));modules=s.modules;runMachine=MACHINES.find(m=>m.id===s.machine);chosenMachine=s.machine;earnedThisRun=false;lesson=s.lesson?{phase:s.lesson.phase,initial:s.lesson.initial,clock:s.lesson.clock,gate:s.lesson.gateIndex>=0?objects[s.lesson.gateIndex]:s.lesson.gate}:null;
 keys={};drag=false;arcs=[];particles=[];floats=[];rings=[];joiners=[];noticeQueue=[];noticeLeft=0;shake=flash=muzzle=beamFlash=toastTime=0;$('toast').style.opacity=0;coach.hidden=true;
 if(lesson){if(lesson.phase==='aim')teach('右の青いゲートをねらおう','下のエリアを右へドラッグ。射撃は自動です。');else if(lesson.phase==='cross')teach('数字が増えた！ ゲートを通ろう','青いゲートに正面から入り、仲間を増やそう。');else teach('増援が合流！ 部隊 '+army+'人','人数で弾幕が進化。装備はこの先のパネルで獲得。');}
 else if(!movedInRun&&elapsed<7)teach('左右にドラッグして移動','青いゲートを撃つと、合流する人数が増えます。');
 battleAudio.musicEnabled=s.audio.music;muted=!battleAudio.enable(s.audio.enabled);$('sound').textContent=muted?'音 OFF':'音 ON';$('music').textContent=s.audio.music?'BGM ON':'BGM OFF';$('music').setAttribute('aria-pressed',String(s.audio.music));$('sound').setAttribute('aria-label',muted?'サウンドをオンにする':'サウンドをオフにする');
 if(typeof restoreExpedition==='function')restoreExpedition(s.expedition);checkpointRunId=r.id;checkpointOwned=true;checkpointRestoring=false;state='playing';recovery.classList.add('hidden');$('pauseMenu').classList.add('hidden');updateHUD();fieldMode();checkpointClock=0;checkpointWrite({...checkpointData,run:{...r,owner:checkpointOwner},profile:checkpointProfile()},{takeover:true});}
finish=function(win){if(state!=='playing'||checkpointFinishing)return;checkpointFinishing=true;state='settling';const settle=()=>{const latest=checkpointRead();if(latest?.lastResult?.id===checkpointRunId||latest&&latest.revision>checkpointData.revision&&latest.run?.owner!==checkpointOwner){checkpointFinishing=false;checkpointOwned=false;state='paused';checkpointMessage('この作戦は別の画面で更新されました。再読み込みしてください。');$('pauseMenu').classList.remove('hidden');return;}
 state='playing';checkpointFinish(win);const baseEarned=win?30+Math.min(30,Math.floor(kills/5)):Math.min(25,Math.floor(kills/5));const earned=typeof resultMaterialEarned==='function'?resultMaterialEarned(baseEarned):baseEarned;checkpointFinishing=false;checkpointOwned=false;
 const ok=checkpointWrite({...checkpointData,profile:checkpointProfile(),run:null,lastResult:{id:checkpointRunId,win,earned,level,score}});storageOK=arsenalSaved=ok;if(!ok){checkpointPendingResult={id:checkpointRunId,win,earned,level,score};$('resultProgress').textContent='結果をまだ保存できていません。この画面を閉じると、前回の中断地点に戻ります。';$('researchResult').textContent='開発素材 +'+earned+'（この画面内のみ・未保存）';}checkpointMenu();};
 if(navigator.locks?.request)navigator.locks.request('breach-run-result',settle).catch(()=>{checkpointFinishing=false;state='paused';checkpointWarning();$('pauseMenu').classList.remove('hidden');});else settle();};
$('continueRun').onclick=restoreCheckpoint;$('restartSavedRun').onclick=()=>{const n=checkpointData.run?.snapshot.values.level||level;start(n,true);};$('closeRecovery').onclick=()=>{recovery.classList.add('hidden');checkpointMenu();};
$('start').onclick=()=>start($('level').value);$('pause').onclick=pause;$('home').onclick=home;$('pauseHome').onclick=home;$('restart').onclick=()=>start(level,true);$('retry').onclick=()=>start(level,true);$('next').onclick=()=>start(level+1,true);
window.addEventListener('pagehide',()=>pause());document.addEventListener('freeze',()=>pause());
window.addEventListener('storage',e=>{if(e.key!==CHECKPOINT_KEY||!checkpointOwned)return;const next=checkpointDecode(e.newValue);if(next&&next.revision>checkpointData.revision&&next.run?.owner!==checkpointOwner){checkpointOwned=false;checkpointPause();checkpointMessage('別の画面でこの作戦を開きました。この画面では進行を止めています。');}});
(function initializeCheckpoint(){let primary=null,backup=null,hadData=false;try{const raw=localStorage.getItem(CHECKPOINT_KEY);hadData=!!raw;primary=checkpointDecode(raw);backup=checkpointDecode(localStorage.getItem(CHECKPOINT_BACKUP));}catch{}
 if(primary?.future){checkpointFrozen=true;checkpointData={revision:0,profile:checkpointProfile(),run:null,lastResult:null};checkpointMessage('新しい版の保存データがあります。保存を保護しています。新しい版で開いてください。');return;}
 checkpointData=primary||(!backup?.future&&backup)||{revision:0,profile:checkpointProfile(),run:null,lastResult:null};checkpointApplyProfile(checkpointData.profile);if(hadData&&!primary)checkpointMessage(backup?'予備の保存データから復元しました。':'中断データを読み取れません。以前の進行記録を使います。');
 if(checkpointData.run&&(!validCheckpointRun(checkpointData.run)||checkpointData.lastResult?.id===checkpointData.run.id)){checkpointData.run=null;checkpointMessage('中断データの形式が変わったため、この作戦は最初からになります。獲得済みの進行記録は保持しています。');}
 checkpointMenu();if(checkpointData.run)showRecovery();})();

bindExerciseRecovery();
