'use strict';
// Generation v1 is immutable: retries/reloads use the same authored-segment seed.
const FRONTIER_VERSION=1;
const coreSegments=document.createElement('div');coreSegments.id='coreSegments';coreSegments.setAttribute('aria-hidden','true');coreSegments.innerHTML='<i></i><i></i><i></i>';$('rushHud').append(coreSegments);
const FRONTIER_GEAR={20:{id:'volt',name:'アーク・クラウン',detail:'Volt覚醒中の連鎖射程と連鎖数を強化'},40:{id:'lance',name:'ヘリオス・レール',detail:'Lance覚醒中の貫通砲を二連化'},60:{id:'swarm',name:'オービット・ラック',detail:'Swarm覚醒中の追撃ドローンを増設'}};
function frontierRng(n){let a=(Math.imul(n,2654435761)^0xb7eac101)>>>0;return()=>{a=(Math.imul(a,1664525)+1013904223)>>>0;return a/4294967296;};}
function frontierPlan(n){const random=frontierRng(n),pick=a=>a[Math.floor(random()*a.length)],band=Math.min(9,Math.floor((n-11)/10)),rest=n%10===1||n%10===6,milestone=n%10===0;
 const pool=['cluster','column','sweep'];if(n>=15)pool.push('shutter');if(n>=21)pool.push('flank');if(n>=31)pool.push('prism');if(n>=41)pool.push('relay');if(n>=51)pool.push('rescue');if(n>=61)pool.push('split');
 const segments=[];let last='';for(let i=0;i<5;i++){let id=pick(pool.filter(x=>x!==last));if(i===0&&n===11)id='sweep';if(i===1&&n===15)id='shutter';if(i===1&&n===21)id='flank';if(i===1&&n===31)id='prism';if(rest&&i===2)id='rescue';segments.push({id,z:31+i*26,side:pick([-1,1]),density:rest?6:8+Math.floor(band/3)+(milestone?2:0)});last=id;}
 return{version:1,seed:(Math.imul(n,2654435761)^0xb7eac101)>>>0,band,rest,milestone,segments,boss:1450+band*45+(milestone?180:0)};
}
function ensureFrontierStages(to=101){for(let n=STAGES.length+1;n<=Math.min(9999,to);n++){const p=frontierPlan(n),relay=p.segments.filter(s=>s.id==='relay').length,rescue=p.segments.filter(s=>s.id==='rescue').length;const m={chapter:'FRONTIER / 第'+Math.ceil(n/10)+'宙域',name:n===100?'百の戦線、その先へ':p.milestone?'宙域要塞 '+n:p.rest?'補給航路 '+n:'未踏戦線 '+n,goal:relay?'中継塔を落とし、要塞の追加砲撃を止める':rescue?'金色の救援信号を回収し、要塞を突破する':'敵の構えと通路を読み、要塞を突破する',tip:'青い増援で部隊を育てる。赤い射線は固定後に横へ回避。再挑戦は同じ配置です。',tools:p.segments.map(s=>({cluster:'密集',column:'盾列',sweep:'掃射',shutter:'開閉壁',flank:'側面突撃',prism:'偏向盾',relay:'中継塔',rescue:'救援',split:'分岐壁'})[s.id]).join(' → '),focus:p.rest?'補給と立て直し':'敵の構えを読む',fieldHint:'赤い予告から離れ、青い弱点へ',theme:n<31?'steel':'night',recommend:p.segments.some(s=>['column','prism','relay'].includes(s.id))?'lance':rescue?'swarm':'volt',boss:p.boss,end:176,relayGoal:relay||undefined,rescueGoal:rescue||undefined};EXPEDITIONS[n]=m;STAGES.push({name:m.name,brief:m.goal});const option=document.createElement('option');option.value=n;option.textContent=String(n).padStart(2,'0')+' '+m.name;$('level').append(option);}}
ensureFrontierStages();
const frontierMakeLevel=makeLevel;
makeLevel=function(){if(level<=10)return frontierMakeLevel();ensureFrontierStages(level+1);const p=frontierPlan(level);objects=[];seed=p.seed;expeditionRun={mission:level,relays:0,rescued:0,missed:0,bossClock:0,bossCycle:-1,bossPhase:'shield',bossAim:0,bossFired:false,wardReady:relicInstalled('guardian'),lastDamageAt:-10,generation:{version:1,seed:p.seed},awakeningClock:0};
 const gate=z=>[6,10,6].forEach((v,i)=>{addGate(z,i,v);objects.at(-1).cap=p.rest?24:Math.max(12,22-p.band);});
 const choice=(z,rescue=false)=>objects.push({type:'pickup',kind:rescue?'reinforce':p.segments.some(s=>s.id==='cluster')?'wide':'reinforce',rescue,z,x:-.49,dead:false,hit:0},{type:'pickup',kind:p.segments.some(s=>['column','prism','relay'].includes(s.id))?'pierce':'blast',z,x:.49,dead:false,hit:0});
 const enemy=(z,x,hp,extra={})=>{addEnemy(z,x,hp);Object.assign(objects.at(-1),extra);};
 gate(10);choice(21);
 for(const s of p.segments){const {z,side,density}=s,hp=16+p.band*.65;
  if(s.id==='cluster'||s.id==='column'){for(let j=0;j<density;j++){const col=s.id==='column';enemy(z+Math.floor(j/(col?2:4))*2.2,(col?(j%2?-.42:.42):(j%4-1.5)*.23)*side,hp,col&&j<2?{shield:45,maxShield:45,armored:true}:{});}}
  if(s.id==='sweep'){enemy(z,.55*side,65,{role:'sweeper',clock:0,aim:0,warn:false,round:0});for(let j=0;j<4+Math.floor(p.band/3);j++)enemy(z+5+j*1.7,-side*.35,hp);}
  if(s.id==='flank'){enemy(z,.72*side,55,{role:'charger',wind:0,aim:null,dashing:false});for(let j=0;j<4;j++)enemy(z+6+j*1.6,-side*.38,hp);}
  if(s.id==='prism'){enemy(z,.4*side,100,{role:'prism',weakSide:-side,clock:0,armored:true});for(let j=0;j<4;j++)enemy(z+4+j*1.8,.4*side,hp);}
  if(s.id==='relay')enemy(z,.43*side,175,{role:'relay',anchor:z,shield:45,maxShield:45,armored:true});
  if(s.id==='shutter'||s.id==='split'){const xs=s.id==='split'?[0,.66*side]:[.66*side];for(const x of xs)objects.push({type:'obstacle',z:z+7,x,dead:false,hit:0,warned:false,frontierWall:s.id,opens:s.id==='shutter'&&side===1});for(let j=0;j<4;j++)enemy(z-2+j*1.5,-side*.55,hp);}
  if(s.id==='rescue'){choice(z,true);for(let j=0;j<4;j++)enemy(z+11+j*1.5,.4*side,hp);}
  if(p.band>=2&&!p.rest&&!['cluster','column','sweep','rescue'].includes(s.id))for(let j=0;j<3+Math.floor(p.band/2);j++)enemy(z+10+Math.floor(j/3)*2,(j%3-1)*.27,hp,j===0&&p.band>=5?{shield:35,maxShield:35,armored:true}:{});
 }
 gate(75);choice(99);gate(125);addEnemy(176,0,p.boss,true);objects.at(-1).fortress=true;totalEnemies=objects.filter(o=>['enemy','boss'].includes(o.type)).length;
};
const frontierRefresh=refreshCampaign;
let frontierPage=0,frontierBrowse=null;
refreshCampaign=function(){ensureFrontierStages(Math.max(101,unlocked()+1));frontierRefresh();const selected=Number($('level').value)||1;frontierPage=frontierBrowse??Math.floor((selected-1)/10);frontierBrowse=null;const cards=[...$('stageGrid').querySelectorAll('[data-stage]')];for(const c of cards)c.hidden=Math.floor((Number(c.dataset.stage)-1)/10)!==frontierPage;for(const h of $('stageGrid').querySelectorAll('.chapter-heading'))h.hidden=frontierPage>0;let nav=$('frontierNav');if(!nav){nav=document.createElement('div');nav.id='frontierNav';$('stageGrid').before(nav);}nav.innerHTML='<button class="textbutton" id="frontierPrev" '+(frontierPage===0?'disabled':'')+'>前の宙域</button><b>'+ (frontierPage*10+1)+'–'+Math.min(STAGES.length,(frontierPage+1)*10)+'</b><button class="textbutton" id="frontierNext" '+((frontierPage+1)*10>=Math.max(100,unlocked())?'disabled':'')+'>次の宙域</button>';
 const page=d=>{frontierBrowse=clamp(frontierPage+d,0,Math.ceil(Math.max(100,unlocked())/10)-1);refreshCampaign();};$('frontierPrev').onclick=()=>page(-1);$('frontierNext').onclick=()=>page(1);$('campaignProgress').textContent=Object.keys(campaign.records).filter(n=>Number(n)<=100).length+' / 100 作戦突破'+(unlocked()>100?' · 限界航路 '+unlocked():'');
};
const frontierHangar=renderHangar;
const frontierMachineArt=machineSVG;
machineSVG=function(id,installed=[],compact=false){let svg=frontierMachineArt(id,installed,compact);if(Object.entries(FRONTIER_GEAR).some(([n,g])=>g.id===id&&campaign.records[n])){const attachment=id==='volt'?'<path d="M20 18 L30 4 43 16 M77 16 L90 4 100 18" fill="none" stroke="#89fff0" stroke-width="6"/>':id==='lance'?'<path d="M26 4 V62 M94 4 V62" stroke="#ffe3a1" stroke-width="7"/>':'<path d="M1 36 H12 V69 H1 Z M108 36 H119 V69 H108 Z" fill="#d8a85b" stroke="#ffe3a1"/>';svg=svg.replace('</svg>',attachment+'</svg>');}return svg;};
renderHangar=function(){frontierHangar();let rack=$('frontierRack');if(!rack){rack=document.createElement('div');rack.id='frontierRack';$('hangarBay').after(rack);}rack.innerHTML=Object.entries(FRONTIER_GEAR).map(([n,g])=>'<p class="'+(campaign.records[n]?'earned':'')+'"><b>'+g.name+'</b><span>'+ (campaign.records[n]?g.detail:'作戦'+n+'で獲得')+'</span></p>').join('');if($('deployFromHangar')&&expeditionVictory?.level===10){$('deployFromHangar').textContent='新装備で未踏戦線11へ';$('deployFromHangar').onclick=()=>start(11,true);}};
const frontierHit=hitEnemy;
const frontierThreshold=gateThreshold;
gateThreshold=function(value){if(level<=10)return frontierThreshold(value);const band=Math.min(9,Math.floor((level-11)/10)),cap=level%10===1||level%10===6?24:Math.max(12,22-band);return value>=cap?Infinity:8+Math.max(0,value-10)*1.4;};
hitEnemy=function(o,damage,kind='rapid'){if(o.role==='prism'){const exposed=(px-o.x)*o.weakSide>.12;damage*=exposed||['pierce','lance'].includes(kind)?1.3:.38;}frontierHit(o,damage,kind);};
const frontierUpdate=update;
update=function(dt){if(state==='playing'&&level>10){for(const o of objects){if(o.dead)continue;const rel=o.z-distance;if(o.frontierWall==='shutter'&&o.opens&&rel<18){o.dead=true;floating('OPEN',o.x,rel,'#88e9e1');}if(o.role==='prism'&&!o.directional){o.clock+=dt;o.weakSide=Math.floor(o.clock/4)%2?1:-1;}if(o.role==='sweeper'&&rel<32&&rel>8){const safe=objects.some(x=>!x.dead&&((x.type==='obstacle'&&x.z-distance<16)||(x.type==='gate'||x.type==='pickup')&&x.z-distance<9)&&x.z-distance>0)||objects.some(x=>!x.dead&&x.type==='hazard');if(!o.warn&&!safe){o.clock+=dt;if(o.clock>1.2){o.aim=o.round%2?(o.aim>=0?-.55:.55):clamp(px,-.55,.55);o.warn=true;o.clock=0;}}else if(o.warn){o.clock+=dt;if(o.clock>1.5){if(!safe)objects.push({type:'hazard',z:o.z-2,x:o.aim,dead:false,source:'mortar'});o.warn=false;o.clock=-.6;o.round++;}}}}}
 frontierUpdate(dt);if(state!=='playing')return;
 if(expeditionRun){expeditionRun.awakeningClock=Math.max(0,(expeditionRun.awakeningClock||0)-dt);if(rush>0&&expeditionRun.awakeningClock<=0){expeditionRun.awakeningClock=.65;const id=runMachine.id,gear=Object.entries(FRONTIER_GEAR).some(([n,g])=>g.id===id&&campaign.records[n]);if(id==='lance'){emitBullet(px,'pierce',55);if(gear)emitBullet(px+.1,'pierce',45);}else if(id==='volt'){const ts=liveTargets().filter(t=>Math.abs(t.x-px)<(gear?.85:.6)).slice(0,gear?5:3);for(const t of ts){hitEnemy(t,24,'volt');arcs.push({a:{x:px,z:distance+2},b:{x:t.x,z:t.z},life:.18});}}else{const ts=liveTargets();for(let i=0;i<(gear?4:2)&&ts.length;i++)missiles.push({x:px+(i%2?.12:-.12),z:distance+2,target:ts[i%ts.length],power:30,life:3});}battleAudio.effect('shot',3);}}
};
const frontierRush=activateRush;
activateRush=function(){frontierRush();if(expeditionRun)expeditionRun.awakeningClock=0;emitBullet(px,'pierce',60);toast({volt:'覚醒 / アーク連鎖',lance:'覚醒 / 貫通砲、展開',swarm:'覚醒 / 追撃ラック解放'}[runMachine.id],runMachine.color);};
const frontierHud=updateHUD;
updateHUD=function(){frontierHud();$('rushLabel').textContent=rush>0?'CORE OPEN · '+rush.toFixed(1)+'秒':'覚醒 '+Math.floor(rushCharge/4)+' / 3 · 撃破で充填';$('rushHud').dataset.charge=rush>0?'3':String(Math.floor(rushCharge/4));};
const frontierObject=drawObject;
drawObject=function(o){if(!['sweeper','prism'].includes(o.role)){frontierObject(o);return;}const rel=o.z-distance;if(rel<0||rel>110)return;const p=project(o.x,rel),s=p.s;unit(p.x,p.y,s*1.5,o.role==='sweeper'?'#d55483':'#817cae',o.phase,true);if(o.role==='sweeper'){for(const side of[-1,1])round(p.x+side*20*s-5*s,p.y-49*s,10*s,36*s,2,'#58384b','#ff8caa');if(o.warn)threatLane(o.aim,rel,'#ff6c81','掃射 / 横へ');}else{const side=o.weakSide;poly([[p.x-side*6*s,p.y-54*s],[p.x-side*30*s,p.y-43*s],[p.x-side*30*s,p.y-8*s],[p.x-side*6*s,p.y]],'#345779','#a4caff');txt(side<0?'弱点 ◀':'▶ 弱点',p.x+side*20*s,p.y-66*s,12,'#90fff0');}if(rel<45)txt(o.role==='sweeper'?'掃射砲':'偏向盾',p.x,p.y-86*s,12,'#f4e3e7');};
const frontierArmy=drawArmy;
drawArmy=function(){frontierArmy();if(!['playing','paused'].includes(state))return;const x=W/2+px*W*.43,y=H*.72,lit=rush>0?3:Math.floor(rushCharge/4),open=rush>0?9:0;ctx.save();for(let i=0;i<3;i++)round(x-15+i*11,y-26,8,6,1,i<lit?runMachine.color:'#243c4c');for(const side of[-1,1]){round(x+side*(23+open)-5,y-60-open,10,37+open,2,'#1d3348',runMachine.color);for(let k=0;k<Math.min(3,tier);k++)round(x+side*(39+k*9)-3,y-20+k*6,6,15,2,'#31556a',runMachine.color);}poly([[x-9-open,y-47],[x,y-53],[x+9+open,y-47],[x+6,y-37],[x-6,y-37]],lit?runMachine.color:'#456779');ctx.restore();};
// Repaint critical warnings/numerals above friendly attack effects.
const frontierDraw=draw;
draw=function(dt){frontierDraw(dt);if(!['playing','paused'].includes(state))return;for(const o of objects){if(o.dead)continue;const rel=o.z-distance;if(rel<0||rel>40)continue;if(o.type==='hazard')drawObject(o);else if(o.warn){threatLane(o.aim,rel,'#ff6c81','射線 / 横へ');if(typeof o.aim2==='number')threatLane(o.aim2,rel,'#ff6c81','射線');}}};
function frontierRewardData(){const m=FRONTIER_GEAR[level];return{level,seed:expeditionRun?.generation?.seed,rank:kills/totalEnemies>=.9?'S':kills/totalEnemies>=.7?'A':'B',kills,total:totalEnemies,damage:damageTaken,combo:bestCombo,awakenings:rushCount,milestone:level%10===0,gear:m||null,first:campaign.records[level]?.clears===1};}
const frontierFinishCampaign=finishCampaignOperation;
finishCampaignOperation=function(){frontierFinishCampaign();if(level<=10)return;const r=frontierRewardData();victorySequence.dataset.scale=r.milestone?'milestone':'normal';const heading=victorySequence.querySelector('.victory-signal h2');heading.textContent=level===100?'100戦線、制覇。':r.milestone?'宙域要塞、撃破。':'戦線、突破。';victorySequence.querySelector('.brief-hero').classList.add('frontier-reward-machine');$('rewardTitle').textContent=r.gear?(r.first?'新武装獲得 / ':'武装獲得済み / ')+r.gear.name:r.milestone?'第'+Math.floor(level/10)+'宙域 制圧記章':'RANK '+r.rank+' / 戦果確定';const details=document.createElement('p');details.textContent=(r.gear?r.gear.detail+'。 ':'')+'撃破 '+r.kills+'/'+r.total+' · 最大'+r.combo+'連撃 · 覚醒'+r.awakenings+'回';$('rewardTitle').after(details);if(level===100)$('campaignNext').textContent='限界航路101へ';window.dispatchEvent(new CustomEvent('breach:reward',{detail:r}));};
function validFrontierProfile(c){return !c.frontier||c.frontier.version===1;}
function validFrontierRun(s){const g=s.expedition?.generation;if(s.values?.level<=10)return !g;if(!g||g.version!==FRONTIER_VERSION||g.seed!==frontierPlan(s.values?.level).seed)return false;return true;}
// A single original impact follows a short quiet beat. No delay affects settlement.
const frontierAudioEffect=battleAudio.effect.bind(battleAudio);
battleAudio.effect=function(kind,intensity=0){if(kind==='win'&&level>10){expeditionTimers.push(setTimeout(()=>frontierAudioEffect('win',intensity),350));return;}frontierAudioEffect(kind,intensity);if(kind==='shot'&&rush>0&&this.enabled&&this.ctx&&this.ctx.currentTime>(this.frontierLayerAt||0)){this.frontierLayerAt=this.ctx.currentTime+.16;this.tone(runMachine.id==='lance'?92:runMachine.id==='volt'?185:130,.08,.04,'triangle',0,45);}};
const frontierDecorateReward=finishCampaignOperation;
finishCampaignOperation=function(){frontierDecorateReward();if(level<=10)return;const r=frontierRewardData(),hero=victorySequence.querySelector('.brief-hero');hero.innerHTML=machineSVG(r.gear?.id||runMachine.id,arsenal.installed||[]);const signal=victorySequence.querySelector('.victory-signal');const art=document.createElement('div');art.className='frontier-arrival';art.innerHTML=machineSVG(r.gear?.id||runMachine.id,arsenal.installed||[]);signal.prepend(art);if(r.milestone){const insignia=document.createElement('b');insignia.className='sector-insignia';insignia.textContent='✦ '+String(level).padStart(3,'0')+' ✦';hero.after(insignia);}commandArtCache.clear();};
const frontierCollectionHangar=renderHangar;
renderHangar=function(){frontierCollectionHangar();const rack=$('frontierRack');const medals=document.createElement('div');medals.className='frontier-medals';medals.setAttribute('aria-label','宙域制圧記章');medals.innerHTML=Array.from({length:10},(_,i)=>{const n=(i+1)*10;return '<span class="'+(campaign.records[n]?'earned':'')+'">'+(campaign.records[n]?'✦ ':'')+n+'</span>';}).join('');rack.append(medals);};
const frontierBrief=missionBriefing;
missionBriefing=function(){frontierBrief();if(level>10){const small=document.createElement('p');small.className='frontier-seed';small.textContent='固定航路 '+frontierPlan(level).seed+' · 再挑戦でも配置は同じ';missionBrief.append(small);}};
refreshCampaign();renderHangar();
