'use strict';
const spriteSheet=typeof Image!=='undefined'?new Image():null;if(spriteSheet)spriteSheet.src='assets/troopers.png';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
let W=400,H=800,dpr=1,state='menu',level=1,elapsed=0,distance=0,army=1,maxArmy=1,kills=0,px=0,targetX=0,objects=[],bullets=[],particles=[],floats=[],shotClock=0,shake=0,flash=0,toastTime=0,muted=true,audio=null,drag=false,lastX=0,keys={},bossAnnounced=false,seed=1,frameTime=0;
let wide=0,piercing=0,support=0,supportClock=0,volley=0,rush=0,rushCharge=0,rushCount=0,tier=0,bestCombo=0,impactChain=0;
let weapon='rapid',weaponLevel=1,combo=0,comboTime=0,score=0,lastDamage='',rings=[],muzzle=0,slowmo=0,bossTime=0,runBest=0;
function bestScore(n){try{return Number(localStorage.getItem('breach-best-v5-'+n))||0}catch{return 0}}
function saveBest(n,value){try{localStorage.setItem('breach-best-v5-'+n,String(value))}catch{}}
const STAGES=[
{name:'突破口',brief:'青いゲートで増援。弾幕を育てよう。',hp:1,boss:2300,chargers:0,mortars:0,forms:'sscccss'},
{name:'突破阻止',brief:'突撃予告を見て、撃破か回避。',hp:1.18,boss:3900,chargers:5,mortars:0,forms:'ssclcsc'},
{name:'砲火の要塞',brief:'赤い照準が止まったら横へ移動。',hp:1.36,boss:5800,chargers:5,mortars:4,forms:'ssclcsc'},
{name:'鋼鉄の列',brief:'盾の隊列には貫通。後列まで撃ち抜け。',hp:1.4,boss:5900,chargers:3,mortars:2,forms:'ssllllc'},
{name:'包囲突破',brief:'左右に広がる敵群をワイドで掃討。',hp:1.45,boss:6100,chargers:5,mortars:2,forms:'sssssss'},
{name:'迫撃回廊',brief:'砲撃兵を優先。照準から離れて反撃。',hp:1.5,boss:6300,chargers:2,mortars:5,forms:'sclclcc'},
{name:'疾走戦線',brief:'連続する突撃。狙いを切り替えろ。',hp:1.55,boss:6500,chargers:7,mortars:2,forms:'sscscsc'},
{name:'重装要塞',brief:'盾と砲撃の混成部隊。貫通が突破の鍵。',hp:1.6,boss:6800,chargers:4,mortars:4,forms:'sslllcl'},
{name:'交差砲火',brief:'左右から迫る敵。撃つ場所と逃げ道を選べ。',hp:1.65,boss:7100,chargers:6,mortars:5,forms:'slsclsc'},
{name:'最終突破',brief:'すべての脅威を突破し、最後の巨兵を倒せ。',hp:1.7,boss:7500,chargers:7,mortars:5,forms:'slcslcl'}
];
const SAVE_KEY='breach-campaign-v1';let storageOK=true,damageTaken=0,totalEnemies=0;
function loadCampaign(){let data={};try{data=JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')||{}}catch{storageOK=false}const records={};for(let n=1;n<=10;n++){let r=data.records?.[n],old=bestScore(n);if(r&&typeof r==='object'&&Number.isFinite(r.score)&&r.score>=0&&r.clears>0){records[n]={score:Math.floor(r.score),stars:Array.from({length:3},(_,i)=>i===0||r.stars?.[i]===true),clears:Math.min(99999,Math.floor(r.clears)),time:Number.isFinite(r.time)&&r.time>0?r.time:0};}else if(old>0)records[n]={score:old,stars:[true,false,false],clears:1,time:0};}return {records};}
let campaign=loadCampaign();
function unlocked(){return Math.min(9999,Math.max(1,...Object.keys(campaign.records).map(n=>Number(n)+1)))}
function persistCampaign(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(campaign));storageOK=true}catch{storageOK=false}}
function selectStage(n){$('level').value=String(clamp(Math.floor(n)||1,1,unlocked()));refreshCampaign();}
function refreshCampaign(){let n=Number($('level').value)||1,r=campaign.records[n];$('stageChoice').textContent=String(n).padStart(2,'0')+'　'+STAGES[n-1].name+'　›';$('stageBrief').textContent=STAGES[n-1].brief;$('campaignProgress').textContent=Object.keys(campaign.records).length+' / 100 作戦突破'+(r?'　BEST '+r.score.toLocaleString():'');$('saveNotice').textContent=storageOK?'進行・記録はこの端末に自動保存':'保存できないため、今回の画面内だけで記録します';$('stageGrid').innerHTML=STAGES.map((s,i)=>{let n=i+1,r=campaign.records[n],locked=n>unlocked();return '<button class="stage-card'+(n===Number($('level').value)?' selected':'')+'" data-stage="'+n+'" '+(locked?'disabled':'')+'><small>OPERATION '+String(n).padStart(2,'0')+'</small><b>'+s.name+'</b><span class="stage-stars">'+(locked?'未解放':r?r.stars.map(v=>v?'★':'☆').join(''):'未クリア')+'</span><span>'+(locked?'作戦 '+String(n-1).padStart(2,'0')+' をクリア':r?'BEST '+r.score.toLocaleString():s.brief)+'</span></button>'}).join('');}
$('stageChoice').onclick=()=>{refreshCampaign();$('stageMenu').classList.remove('hidden')};
$('closeStages').onclick=()=>$('stageMenu').classList.add('hidden');
$('stageGrid').onclick=e=>{const card=e.target.closest('[data-stage]');if(!card||card.disabled)return;selectStage(Number(card.dataset.stage));$('stageMenu').classList.add('hidden')};
const WEAPONS={rapid:{name:'ラピッド',tag:'連射',color:'#91f5df',interval:.11,power:.30,speed:88},pierce:{name:'レール',tag:'貫通',color:'#91bbff',interval:.28,power:.91,speed:120},blast:{name:'ブラスト',tag:'範囲',color:'#ffce88',interval:.95,power:1.22,speed:58}};
const LENGTH=180,SPEED=3.2,LANES=[-.66,0,.66],COLORS=['#6895a7','#b49270','#718896'];
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function resize(){const b=canvas.getBoundingClientRect();W=b.width;H=b.height;dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
window.addEventListener('resize',resize);resize();
function sound(freq=440,duration=.06,type='sine',volume=.025){if(muted)return;battleAudio.effect(freq<=90?'boom':freq<=150?'hurt':freq>=650?'upgrade':freq<=165?'warn':'hit');}
$('sound').onclick=()=>{muted=!battleAudio.enable(muted);$('sound').textContent=muted?'音 OFF':'音 ON';$('sound').setAttribute('aria-label',muted?'サウンドをオンにする':'サウンドをオフにする');if(!muted)battleAudio.effect('upgrade');};
$('music').onclick=()=>{battleAudio.musicEnabled=!battleAudio.musicEnabled;$('music').textContent=battleAudio.musicEnabled?'BGM ON':'BGM OFF';$('music').setAttribute('aria-pressed',String(battleAudio.musicEnabled));};
function toast(text,color='#b9ffe1'){ $('toast').textContent=text;$('toast').style.color=color;$('toast').style.opacity='1';toastTime=1.5 }
function firepower(){return army<=140?army:140+Math.pow(army-140,.65);}
function gateThreshold(value){return 3.8+Math.min(level,3)*.75+Math.max(0,value-30)*.20;}
function addGate(z,lane,value){objects.push({type:'gate',z,x:LANES[lane],value,hit:0,progress:0,dead:false})}
function addEnemy(z,x,hp,boss=false){objects.push({type:boss?'boss':'enemy',z,x,hp,maxHp:hp,hit:0,dead:false,attack:0,phase:rand()*6})}
function makeLevel(){objects=[];seed=level*752+4;const config=STAGES[level-1],mirror=level>3&&level%2===0?-1:1;
for(const r of [{z:12,v:[3,6,3]},{z:69,v:[10,-4,8]},{z:130,v:[12,8,-6]}])r.v.forEach((v,j)=>addGate(r.z,j,v));
for(const [z,kinds] of [[25,['reinforce','wide']],[82,['reinforce','pierce']],[139,['wide','blast']]])for(let j=0;j<2;j++)objects.push({type:'pickup',kind:kinds[j],z,x:j===0?-.49:.49,dead:false,hit:0});
const waves=[{z:32,n:12,hp:4,form:'sweep'},{z:48,n:18,hp:7,form:'sweep'},{z:60,n:18,hp:8,form:'cluster'},{z:94,n:24,hp:11,form:'column'},{z:114,n:30,hp:10,form:'cluster'},{z:150,n:30,hp:13,form:'sweep'},{z:166,n:24,hp:14,form:'cluster'}];
if(level>3)waves.forEach((w,i)=>{w.form=({s:'sweep',c:'cluster',l:'column'})[config.forms[i]];});
for(const w of waves)for(let j=0;j<w.n;j++){let x,z;if(w.form==='sweep'){x=(j%6-2.5)*.26;z=w.z+Math.floor(j/6)*2.4+Math.sin(j%6)*1.5}else if(w.form==='column'){x=(j%3-1)*.56;z=w.z+Math.floor(j/3)*2.0}else{x=(j%6-2.5)*.18;z=w.z+Math.floor(j/6)*1.8}addEnemy(z,x*mirror,w.hp*config.hp);let e=objects[objects.length-1];e.group=w.z;e.form=w.form;if(w.form==='column'&&j<3){e.shield=12+Math.min(level,5)*5;e.maxShield=e.shield;e.armored=true}}
for(const [z,x] of [[54,.66],[119,-.66]])objects.push({type:'crate',z,x,hp:18,maxHp:18,reward:10,hit:0,dead:false});
const chargerSpots=[[78,-.66],[102,.66],[128,-.66],[151,.66],[173,-.66],[90,.66],[140,-.66]];
const mortarSpots=[[92,.66],[117,-.66],[144,.66],[170,-.66],[105,.66]];
for(const [z,x] of chargerSpots.slice(0,config.chargers)){addEnemy(z,x*mirror,240+z*3);Object.assign(objects[objects.length-1],{role:'charger',wind:0,aim:null,dashing:false});}
for(const [z,x] of mortarSpots.slice(0,config.mortars)){addEnemy(z,x*mirror,350+z*4);Object.assign(objects[objects.length-1],{role:'mortar',attack:.8,warn:false,aim:0});}
// Spaced away from gates/upgrades. No row blocks all three lanes.
const obstacleRows=level===1?[]:level<=3?[[43,[1]],[108,[level%2?0:2]]]:level<=6?[[43,[1]],[90,[0]],[123,[2]],[148,[1]]]:[[43,[0,2]],[90,[1]],[108,[level%2?0:2]],[123,[0,2]],[148,[1]]];
for(const [z,lanes] of obstacleRows)for(const lane of lanes)objects.push({type:'obstacle',z,x:LANES[lane],dead:false,hit:0,warned:false});
addEnemy(179,0,config.boss*(1+Math.max(0,level-1)*.025),true);totalEnemies=objects.filter(o=>o.type==='enemy'||o.type==='boss').length;
}
function equip(kind){if(kind==='reinforce'){changeArmy(20);toast('増援 +20  /  弾幕強化');return}if(kind==='wide'){wide=Math.min(3,wide+1);toast('ワイド +'+wide+'  /  横一列を薙ぎ払え')}if(kind==='pierce'){piercing=Math.min(3,piercing+1);toast('貫通 +'+piercing+'  /  奥まで撃ち抜け','#a8cfff')}if(kind==='blast'){support=Math.min(3,support+1);supportClock=0;toast('榴弾支援  /  連射に追加攻撃','#ffe0a3')}rings.push({x:px,z:1,life:.5,max:.5,color:'#a5f4d7'});sound(850,.17,'triangle',.04);haptic(12)}
function activateRush(){rush=6;rushCharge=0;rushCount++;toast('RUSH!  6秒間、全砲門解放！','#ffe7a5');battleAudio.effect('rush');haptic(25)}
function emitBullet(x,kind,damage,vx=0){bullets.push({x,z:2,damage,kind,color:kind==='blast'?'#ffce88':kind==='pierce'?'#91bbff':rush>0?'#ffe8a2':'#c4ffff',speed:kind==='blast'?65:100,remaining:kind==='pierce'?4+piercing:1,hits:[],vx})}
function haptic(ms){if(typeof navigator!=='undefined'&&navigator.vibrate)navigator.vibrate(ms)}
function hitEnemy(o,damage){if(o.dead)return;if(o.shield>0){o.shield-=damage;o.hit=.1;if(o.shield>0)return;o.shield=0;rings.push({x:o.x,z:o.z-distance,life:.3,max:.3,color:'#9bcfff'});burst(o.x,o.z-distance,'#cbe6ff',12);floating('BREAK',o.x,o.z-distance,'#b4dfff');sound(320,.08,'triangle',.025);return}o.hp-=damage;o.hit=.09;battleAudio.effect('hit');burst(o.x,o.z-distance,WEAPONS[weapon].color,2);if(o.hp>0)return;o.dead=true;burst(o.x,o.z-distance,o.type==='crate'?'#ffdb86':'#ff9b88',o.type==='boss'?60:12);rings.push({x:o.x,z:o.z-distance,life:.3,max:.3,color:o.type==='crate'?'#ffdf8f':'#ff9f8e'});if(o.type==='crate'){changeArmy(o.reward);toast('増援 +'+o.reward)}else{kills++;if(o.type==='enemy'&&rush<=0){rushCharge++;if(rushCharge>=12)activateRush();}impactChain++;combo++;bestCombo=Math.max(bestCombo,combo);comboTime=2.7;score+=Math.round(100*(1+Math.min(combo,20)*.08));battleAudio.effect('kill',combo);if(combo%5===0)floating(combo+' COMBO',o.x,o.z-distance,'#ffe7a1');if(o.type==='boss'){distance=LENGTH;score+=2000+army*15;slowmo=.7;finish(true)}}}
function start(n=level){level=clamp(Math.floor(Number(n))||1,1,unlocked());damageTaken=0;$('level').value=String(level);state='playing';wide=piercing=support=supportClock=volley=rush=rushCharge=rushCount=tier=bestCombo=0;$('rushHud').style.display='block';weapon='rapid';weaponLevel=1;combo=comboTime=score=0;lastDamage='';runBest=bestScore(level);rings=[];muzzle=slowmo=bossTime=0;elapsed=distance=0;army=maxArmy=1;kills=0;keys={};drag=false;px=targetX=0;bullets=[];particles=[];floats=[];shotClock=0;shake=flash=0;bossAnnounced=false;makeLevel();for(const id of ['menu','result','pauseMenu','stageMenu'])$(id).classList.add('hidden');$('hud').style.display='flex';$('pause').style.display='block';$('footer').style.display='block';$('hint').style.display='block';$('stageName').textContent='OPERATION '+String(level).padStart(2,'0');toast(STAGES[level-1].brief);sound(600,.15);updateHUD()}
function home(){state='menu';battleAudio.tick(false,false);$('app').classList.remove('rushing');$('rushHud').style.display='none';$('menu').classList.remove('hidden');$('result').classList.add('hidden');$('pauseMenu').classList.add('hidden');$('hud').style.display='none';$('pause').style.display='none';$('footer').style.display='none';$('hint').style.display='none';$('weaponHud').style.display='none';$('toast').style.opacity=0;army=40;px=0;distance=25;level=Number($('level').value);objects=[];bullets=[];particles=[];refreshCampaign()}
function pause(){if(state!=='playing')return;state='paused';battleAudio.tick(false,false);drag=false;keys={};$('pauseMenu').classList.remove('hidden')}
function resume(){if(state!=='paused')return;state='playing';$('pauseMenu').classList.add('hidden')}
function finish(win){if(state!=='playing')return;state=win?'won':'lost';drag=false;const medals=[win,win&&kills/totalEnemies>=.85,win&&damageTaken===0];
if(win){const old=campaign.records[level];campaign.records[level]={score:Math.max(score,old?.score||0),stars:medals.map((v,i)=>v||old?.stars[i]===true),clears:(old?.clears||0)+1,time:Math.min(elapsed,old?.time||Infinity)};if(score>runBest)saveBest(level,score);persistCampaign();}
$('result').classList.remove('hidden');$('resultTitle').textContent=win?(level===100?'100作戦、突破！':'戦線突破！'):'部隊、全滅';$('maxStat').textContent=maxArmy;$('killStat').textContent=kills+' / '+totalEnemies;$('distStat').textContent=Math.floor(distance)+'m';$('next').classList.toggle('hidden',!win||level===9999);$('pause').style.display='none';$('hint').style.display='none';
$('resultText').textContent=win?'スコア '+score.toLocaleString()+(score>runBest?' ｜ 自己ベスト更新！':' ｜ BEST '+runBest.toLocaleString()):lastDamage||'増援を狙って、もう一度挑戦しよう。';$('resultText').textContent+=' ｜ RUSH '+rushCount+'回 / 最大 '+bestCombo+'連続撃破';
$('resultTag').textContent=win?(kills/totalEnemies>=.9?'S':kills/totalEnemies>=.7?'A':'B')+' RANK / MISSION COMPLETE':'MISSION FAILED';
$('medals').innerHTML=['作戦クリア','85% 撃破','被害ゼロ'].map((label,i)=>'<span class="'+(medals[i]?'earned':'')+'">'+(medals[i]?'★':'☆')+'<small>'+label+'</small></span>').join('');
$('resultProgress').textContent=win?(level<9999?'作戦 '+String(level+1).padStart(2,'0')+' に挑戦できます。':'最深部まで到達！ 各作戦の★3つにも挑戦しよう。')+(storageOK?' 記録を保存しました。':' 保存できませんでした。画面を閉じると今回の記録は失われます。'):'★はクリア時に獲得。作戦選択から得意な戦線にも挑戦できます。';
$('rushHud').style.display='none';battleAudio.effect(win?'win':'lose');haptic(win?35:70)}
$('start').onclick=()=>start($('level').value);$('retry').onclick=()=>start();$('restart').onclick=()=>start();$('next').onclick=()=>start(level+1);$('home').onclick=home;$('pauseHome').onclick=home;$('pause').onclick=pause;$('resume').onclick=resume;
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});window.addEventListener('blur',()=>{keys={};pause()});
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;drag=true;lastX=e.clientX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;targetX=clamp(targetX+(e.clientX-lastX)/(W*.39),-.8,.8);lastX=e.clientX});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>drag=false);
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','a','A','d','D',' ','Escape'].includes(e.key)){if(state!=='menu')e.preventDefault();keys[e.key.toLowerCase()]=true;if(e.key==='Escape'||e.key===' '){if(state==='playing')pause();else if(state==='paused')resume()}}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function project(x,z){let d=clamp(z,0,110)/110,t=Math.pow(1-d,1.65),s=.14+.86*t;return {x:W/2+x*W*.43*s,y:H*.235+H*.485*t,s}}
function poly(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function round(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
function txt(text,x,y,size,color='#fff',weight=800){ctx.font=weight+' '+size+'px Arial,"Noto Sans CJK JP",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(text,x,y)}
function unit(x,y,s,color='#42a9ef',phase=0,heavy=false){if(spriteSheet?.complete&&spriteSheet.naturalWidth){let index=!heavy?0:color==='#f69b43'?2:color==='#d55483'?3:1;let cw=spriteSheet.naturalWidth/2,ch=spriteSheet.naturalHeight/2;ctx.fillStyle='#05152555';ctx.beginPath();ctx.ellipse(x+3*s,y+2*s,10*s,4*s,0,0,7);ctx.fill();let bob=Math.sin(frameTime*12+phase)*.7*s;ctx.drawImage(spriteSheet,(index%2)*cw,Math.floor(index/2)*ch,cw,ch,x-21*s,y-39*s+bob,42*s,42*s);return;}ctx.save();ctx.translate(x,y);ctx.scale(s,s);let walk=Math.sin(frameTime*12+phase)*2;ctx.fillStyle='#07162465';ctx.beginPath();ctx.ellipse(4,4,10,5,0,0,7);ctx.fill();
// Lit toy-soldier geometry, with distinct helmet, shoulder plates and weapon.
ctx.lineCap='round';ctx.strokeStyle='#102439';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-4,-5);ctx.lineTo(-5,2+walk);ctx.moveTo(4,-5);ctx.lineTo(5,2-walk);ctx.stroke();round(-8,walk,6,4,2,'#182537');round(2,-walk,6,4,2,'#182537');
let armor=ctx.createLinearGradient(-8,0,9,0);armor.addColorStop(0,color);armor.addColorStop(.45,color);armor.addColorStop(1,'#20374e');round(-8,-21,16,17,5,armor);round(-10,-21,6,8,3,color);round(5,-21,6,8,3,color);round(-5,-17,10,9,2,'#19394d');ctx.fillStyle='#ffffff50';ctx.fillRect(-6,-20,10,2);ctx.fillStyle='#6fd7f4';ctx.fillRect(-3,-15,2,3);ctx.fillRect(1,-15,2,3);round(-6,-28,12,9,3,'#b3b9b3');
let helmet=ctx.createLinearGradient(-8,-36,8,-24);helmet.addColorStop(0,'#e0f4ff');helmet.addColorStop(.20,color);helmet.addColorStop(1,'#23354c');round(-9,-37,18,15,7,helmet);round(-7,-28,14,5,2,'#112238');ctx.fillStyle=heavy?'#ffdb98':'#a1f2ff';ctx.fillRect(-5,-27,10,2);ctx.fillStyle='#ffffff66';ctx.fillRect(-5,-34,7,2);
round(7,-34,5,22,2,'#142337');round(8,-38,3,12,1,'#b6c9cd');ctx.fillStyle='#ffffff65';ctx.fillRect(8,-24,2,7);ctx.restore()}
function burst(x,z,color,n=10){for(let i=0;i<n;i++)particles.push({x,z,y:0,vx:(rand()-.5)*.9,vz:(rand()-.5)*8,vy:30+rand()*35,life:.4+rand()*.4,color})}
function floating(text,x,z,color='#b9ffe1'){floats.push({text,x,z,life:1.2,color})}
function changeArmy(n){if(n<0)damageTaken-=n;let before=army;army=Math.max(0,Math.round(army+n));maxArmy=Math.max(maxArmy,army);if(n>0){sound(700,.1);floating('+'+(army-before),px,2);burst(px,1,'#92ffdf',20);rings.push({x:px,z:1,life:.5,max:.5,color:'#92ffdf'});haptic(12)}else{shake=6;flash=.2;sound(120,.12,'sawtooth');floating(String(n),px,2,'#ff9696')}let t=army>=50?3:army>=25?2:army>=10?1:0;if(t>tier){tier=t;toast(['','10人突破！ 2連弾幕','25人突破！ 3連弾幕','50人突破！ 4連弾幕'][tier]);}if(army<=0)finish(false)}
function updateHUD(){$('distance').innerHTML=Math.max(0,Math.ceil(LENGTH-distance))+'<span> m</span>';$('count').textContent=army;$('progress').style.width=(distance/LENGTH*100)+'%';$('weaponHud').style.display='flex';$('weaponName').textContent=[wide?'ワイド '+wide:'',piercing?'貫通 '+piercing:'',support?'榴弾 '+support:''].filter(Boolean).join(' / ')||'連射';$('weaponType').textContent='常時弾幕';$('combo').textContent=combo>1?combo+' COMBO':'';let next=army<10?10:army<25?25:army<50?50:0;$('growth').textContent=next?'あと'+(next-army)+'人で進化':'最大段階の弾幕';$('rushLabel').textContent=rush>0?'RUSH  '+rush.toFixed(1)+'秒':'あと'+(12-rushCharge)+'体で RUSH';$('rushFill').style.width=(rush>0?rush/6*100:rushCharge/12*100)+'%';$('app').classList.toggle('rushing',rush>0&&state==='playing')}
function update(dt){if(state!=='playing')return;elapsed+=dt;rush=Math.max(0,rush-dt);if(elapsed>7)$('hint').textContent='このエリアを左右にドラッグ';comboTime-=dt;if(comboTime<=0)combo=0;if(keys.arrowleft||keys.a)targetX-=dt*1.9;if(keys.arrowright||keys.d)targetX+=dt*1.9;targetX=clamp(targetX,-.8,.8);px+=(targetX-px)*Math.min(1,dt*19);let boss=objects.find(o=>o.type==='boss'&&!o.dead),holding=boss&&boss.z-distance<23;distance=Math.min(LENGTH,distance+(holding?0:SPEED*dt));if(holding)bossTime+=dt;if(distance>140&&!bossAnnounced){bossAnnounced=true;toast('WARNING  /  巨大兵器、接近','#ffb4a3');sound(160,.4,'sawtooth')}
shotClock-=dt;supportClock-=dt;muzzle=Math.max(0,muzzle-dt);if(shotClock<=0){shotClock=rush>0?.065:.105;volley++;let streams=Math.min(15,Math.max(1,Math.ceil(army/4))),width=Math.min(.58,(Math.sqrt(army)-1)*.048);let multi=1+(army>=10?1:0)+(army>=25?1:0)+(army>=50?1:0);for(let i=0;i<streams;i++){let x=px+(streams===1?0:(i/(streams-1)-.5)*width);let kind=piercing>0&&volley%3===0?'pierce':'rapid';emitBullet(x,kind,Math.max(.8,firepower()/streams*.40)*(rush>0?1.2:1));if(multi>1){for(let j=1;j<multi;j++)emitBullet(x+(j-(multi-1)/2)*.014,kind,Math.max(.4,firepower()/streams*.20),0)}}for(let i=1;i<=wide;i++){emitBullet(px,'rapid',Math.max(1,firepower()*.12),i*.23);emitBullet(px,'rapid',Math.max(1,firepower()*.12),-i*.23)}muzzle=.05;battleAudio.effect('shot',multi)}if(support>0&&supportClock<=0){supportClock=rush>0?.75:2.0/(1+(support-1)*.3);emitBullet(px,'blast',45);sound(85,.11,'triangle',.025)}
for(const b of bullets){if(b.dead)continue;let old=b.z;b.z+=dt*b.speed;b.x+=(b.vx||0)*dt;let targets=objects.filter(o=>!o.dead&&o.type!=='pickup'&&o.type!=='hazard'&&o.type!=='obstacle'&&(o.type!=='boss'||o.z-distance<36)&&(o.type!=='enemy'||o.z-distance<(expeditionActive()?34:58))&&!b.hits.includes(o)&&o.z-distance>=old-1&&o.z-distance<=b.z+1&&Math.abs(o.x-b.x)<(o.type==='gate'?.30:o.type==='boss'?.42:o.type==='crate'?.20:.14)).sort((a,b)=>a.z-b.z);
for(const o of targets){if(b.dead)break;b.hits.push(o);o.hit=.09;if(o.type==='gate'){b.dead=true;o.progress+=Math.min(b.damage,3.6);while(o.progress>=gateThreshold(o.value,o)){o.progress-=gateThreshold(o.value,o);o.value++}}else{impactChain=0;hitEnemy(o,b.damage*(o.shield>0&&b.kind==='pierce'?1.8:1),b.kind);b.remaining--;if(b.kind==='blast'){rings.push({x:o.x,z:o.z-distance,life:.35,max:.35,color:'#ffca7b'});for(const neighbor of objects){if(neighbor!==o&&!neighbor.dead&&['enemy','boss','crate'].includes(neighbor.type)&&Math.abs(neighbor.x-o.x)<.72&&Math.abs(neighbor.z-o.z)<6)hitEnemy(neighbor,b.damage*(neighbor.armored?.28:.85))}if(impactChain>=3){floating(impactChain+'体 一掃！',o.x,o.z-distance,'#ffe4a8');sound(70,.22,'sawtooth',.045);}shake=Math.max(shake,4)}if(b.remaining<=0)b.dead=true}}if(b.z>110)b.dead=true}
bullets=bullets.filter(b=>!b.dead);if(state!=='playing'){updateHUD();return}
for(const o of objects){if(o.dead)continue;o.hit=Math.max(0,o.hit-dt);let rel=o.z-distance;if(o.type==='obstacle'){if(rel<24&&!o.warned){o.warned=true;toast('危険！ 障害物は撃てない・横に避けよう','#ffc087');}if(rel<2.2){o.dead=true;if(Math.abs(o.x-px)<.29){lastDamage='障害物に接触。黄黒のバリケードは撃っても消えないので、空いたレーンへ。';changeArmy(-Math.max(6,Math.ceil(army*(level<=3?.25:level<=6?.32:.4))));burst(o.x,2,'#ffad69',20);}}}else if(o.type==='gate'&&rel<1.8){o.dead=true;if(Math.abs(o.x-px)<=.335){lastDamage='赤いゲートで部隊が減少。次は青いゲートを狙おう。';changeArmy(o.value)}}else if(o.type==='pickup'&&rel<1.8){o.dead=true;if((o.x<0&&px<0)||(o.x>0&&px>=0))equip(o.kind)}else if(o.type==='crate'&&rel<0)o.dead=true;else if(o.type==='enemy'){
if(o.role==='charger'&&rel<24){if(o.aim===null){o.aim=px;toast('突撃予告！ オレンジの兵を狙え','#ffbc82')}o.wind+=dt;if(o.wind>1.05){o.dashing=true;o.x+=(o.aim-o.x)*Math.min(1,dt*5);o.z-=dt*21;}}
if(o.role==='mortar'&&rel<34&&rel>5){o.attack+=dt;if(!o.warn&&o.attack>1.0){o.warn=true;o.aim=px;toast('砲撃予告！ 赤い照準から移動','#ffaeae')}if(o.attack>2.15){o.attack=0;o.warn=false;if(objects.filter(e=>e.type==='hazard'&&!e.dead).length<3){objects.push({type:'hazard',x:o.aim,z:o.z-1,dead:false,source:'mortar'});sound(80,.14,'triangle',.025);}}}
o.z-=dt*(rel<45?(o.role?1:2.2):0);if(rel<15&&!o.role)o.x+=(px-o.x)*dt*.4;if(o.z-distance<2.2){o.dead=true;if(Math.abs(o.x-px)<.30){lastDamage=o.role==='charger'?'突撃兵に突破された。オレンジの予告中に撃破するか、突撃する列から離れよう。':o.armored?'盾持ちに突破された。貫通を追加して前後をまとめて狙おう。':'撃ち残した敵に突破された。照準を左右に振って掃討しよう。';changeArmy(o.role==='charger'?-Math.max(8,Math.ceil(army*.34)):-Math.max(2,Math.ceil(o.hp/7)));burst(o.x,2,'#ff827f')}}}else if(o.type==='boss'&&(holding||(level>=2&&rel<36))){o.attack+=dt;let period=level>=3?Math.max(1.7,1.9-(level-3)*.025):2.6;if(!o.warn&&o.attack>period-.85){o.warn=true;o.aim=px;toast('赤い照準から離れよう','#ffb5a4')}if(o.attack>period){o.attack=0;o.warn=false;let lanes=level>=3&&o.hp<o.maxHp*.5?[o.aim,clamp(-o.aim,-.66,.66)]:[o.aim];for(const x of lanes)objects.push({type:'hazard',x,z:o.z-2,dead:false});sound(80,.18,'sawtooth',.03)}}else if(o.type==='hazard'){o.z-=dt*20;if(o.z-distance<2){o.dead=true;if(Math.abs(o.x-px)<.23){lastDamage=o.source==='mortar'?'砲撃兵の弾に命中。赤い予告の列から離れ、砲撃兵を優先して狙おう。':'ボスの砲撃に命中。赤い照準が固定されたら横へ移動しよう。';changeArmy(-Math.max(8,Math.round(army*(o.source==='mortar'?.30:.25))))}}}if(state!=='playing')break}
objects=objects.filter(o=>!o.dead);if(state==='playing'&&!objects.some(o=>o.type==='boss')&&distance>=LENGTH)finish(true);updateHUD()}
function background(){let sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#0c1c34');sky.addColorStop(.45,level===2?'#b08868':level===3?'#67789b':'#8eb4c3');sky.addColorStop(1,'#354c5b');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);ctx.fillStyle='#d4f3e425';ctx.beginPath();ctx.arc(W*.78,H*.16,38,0,7);ctx.fill();poly([[0,H*.24],[W*.2,H*.13],[W*.35,H*.32],[W*.58,H*.16],[W*.78,H*.31],[W,H*.2],[W,H],[0,H]],'#27445b');poly([[0,H*.39],[W*.17,H*.27],[W*.31,H*.52],[W*.51,H*.34],[W*.72,H*.52],[W,H*.3],[W,H],[0,H]],'#193448');let a=project(-1.13,110),b=project(1.13,110);poly([[a.x,a.y],[b.x,b.y],[W*1.03,H*.76],[W*1.03,H],[W*-.03,H],[W*-.03,H*.76]],'#172937');let top=project(-1,110),top2=project(1,110),bottom=project(-1,-1),bottom2=project(1,-1);poly([[top.x,top.y],[top2.x,top2.y],[bottom2.x,bottom2.y],[W*.98,H],[W*.02,H],[bottom.x,bottom.y]],'#526775');
// Receding deck panels, amber hazard rails and cyan lane studs.
for(let z=0;z<112;z+=12){let zz=z-distance%12,a=project(-.98,zz),b=project(.98,zz),c=project(.98,zz+5),d=project(-.98,zz+5);poly([[a.x,a.y],[b.x,b.y],[c.x,c.y],[d.x,d.y]],'#12283b20');}
for(let z=0;z<110;z+=10){let zz=z-distance%10;for(let side of [-1,1]){let p=project(side*.91,zz),q=project(side*.91,zz+3);ctx.strokeStyle=side<0?'#f5be65':'#87dce5';ctx.lineWidth=3*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}
// Receding bridge tiles and lane markings.
for(let z=0;z<110;z+=6){let zz=z-(distance%6),l=project(-1,zz),r=project(1,zz);ctx.strokeStyle='#dbe6de14';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(l.x,l.y);ctx.lineTo(r.x,r.y);ctx.stroke();for(let x of [-.333,.333]){let p=project(x,zz),q=project(x,zz+2.5);ctx.strokeStyle='#d4e1df40';ctx.lineWidth=1.5*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}
for(let side of [-1,1]){let p=project(side*1.02,110);poly([[p.x,p.y-5],[p.x+side*6,p.y-5],[W/2+side*W*.465,H*.72],[W/2+side*W*.51,H],[W/2+side*W*.48,H],[W/2+side*W*.437,H*.72]],'#a3b4b4');for(let z=0;z<112;z+=8){let p=project(side*1.05,z-distance%8);let w=14*p.s,h=26*p.s;round(p.x-w/2,p.y-h,w,h,1,'#81989d');ctx.fillStyle='#b2c4c5';ctx.fillRect(p.x-w/2,p.y-h,w,4*p.s)}}}
function threatLane(x,z,color,label){let a=project(x,0),b=project(x,z);ctx.save();ctx.globalAlpha=.16;poly([[a.x-27,a.y+10],[a.x+27,a.y+10],[b.x+10,b.y],[b.x-10,b.y]],color);ctx.globalAlpha=.8;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(a.x-27,a.y);ctx.lineTo(b.x-10,b.y);ctx.moveTo(a.x+27,a.y);ctx.lineTo(b.x+10,b.y);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.ellipse(a.x,a.y,24,9,0,0,7);ctx.stroke();ctx.globalAlpha=1;round(a.x-33,a.y+13,66,20,5,'#1a2638');txt(label,a.x,a.y+23,12,color);ctx.restore()}
function drawObject(o){let rel=o.z-distance;if(rel>110||rel<-.5)return;let p=project(o.x,rel),s=p.s;if(o.type==='gate'){let w=W*.255*s,h=48*s;let positive=o.value>=0;let color=positive?'#268eb8':'#af435b';ctx.fillStyle='#0d26344d';ctx.beginPath();ctx.ellipse(p.x,p.y+4*s,w*.52,7*s,0,0,7);ctx.fill();poly([[p.x-w/2,p.y],[p.x+w/2,p.y],[p.x+w/2+5*s,p.y-5*s],[p.x-w/2+5*s,p.y-5*s]],'#122e44');round(p.x-w/2,p.y-h,w,h,4*s,o.hit>0?'#defff6':color,positive?'#8be8f5':'#fd8892');ctx.fillStyle=positive?'#62dcea':'#ec748b';ctx.fillRect(p.x-w/2,p.y-h,w,4*s);for(let side of [-1,1]){ctx.fillStyle='#c9dadd';ctx.fillRect(p.x+side*w/2-2*s,p.y-h-4*s,4*s,h+9*s)}txt((positive?'+':'')+o.value,p.x,p.y-h*.49,Math.max(17,31*s),o.hit>0?'#153645':'#fff');}
else if(o.type==='pickup'){let color=o.kind==='reinforce'?'#a7f6d5':o.kind==='wide'?'#a7f6d5':WEAPONS[o.kind].color;let name=o.kind==='reinforce'?'増援 +20':o.kind==='wide'?'ワイド追加':o.kind==='pierce'?'貫通追加':'榴弾支援';let w=W*.39*s;ctx.globalAlpha=.14;round(p.x-w/2,p.y-70*s,w,74*s,5*s,color);ctx.globalAlpha=1;round(p.x-w/2,p.y-46*s,w,37*s,5*s,'#173448',color);txt(name,p.x,p.y-28*s,Math.max(13,17*s),color);txt(o.kind==='reinforce'?'+20':o.kind==='wide'?'≋':o.kind==='pierce'?'↑↑':'●',p.x,p.y-65*s,Math.max(16,23*s),color);txt(o.kind==='reinforce'?'人数UP':o.kind==='wide'?'横に広がる':o.kind==='pierce'?'後列まで貫く':'連射＋爆発',p.x,p.y+5*s,Math.max(10,12*s),'#e9f7ff');}
else if(o.type==='crate'){let w=36*s,h=43*s;poly([[p.x-w/2,p.y-h],[p.x,p.y-h-9*s],[p.x+w/2,p.y-h],[p.x,p.y-h+8*s]],'#f8d994');round(p.x-w/2,p.y-h,w,h,3*s,o.hit>0?'#fff3d2':'#ac773e','#fbd987');ctx.fillStyle='#dfb774';ctx.fillRect(p.x-3*s,p.y-h,6*s,h);txt(Math.ceil(o.hp),p.x,p.y-23*s,Math.max(11,18*s));txt('+'+o.reward,p.x,p.y-h-18*s,Math.max(10,14*s),'#ffe9a1');}
else if(o.type==='enemy'){
if((o.role==='charger'&&o.aim!==null)||o.warn)threatLane(o.aim,rel,o.role==='charger'?'#ffb24d':'#ff5678',o.role==='charger'?'突撃ルート':'砲撃注意');
let color=o.hit>0?'#fff':o.role==='charger'?'#f69b43':o.role==='mortar'?'#d55483':o.armored?'#817cae':'#d1606d';unit(p.x,p.y,s*(o.role?1.7:o.armored?1.65:1.2),color,o.phase,true);
if(o.shield>0)round(p.x-10*s,p.y-20*s,20*s,21*s,4*s,'#427899','#bedfff');
if(o.role==='charger'){poly([[p.x-10*s,p.y-40*s],[p.x,p.y-54*s],[p.x+10*s,p.y-40*s]],'#ffb24d');}if(o.role==='mortar'&&!spriteSheet?.naturalWidth){round(p.x-17*s,p.y-27*s,34*s,13*s,4*s,'#773458','#ff9abe');round(p.x-6*s,p.y-50*s,12*s,32*s,3*s,'#ad657d','#ffd3df');}if(o.role){let w=42*s;round(p.x-w/2,p.y-60*s,w,4*s,2*s,'#142638');round(p.x-w/2,p.y-60*s,w*Math.max(0,o.hp/o.maxHp),4*s,2*s,color);if(rel<60)txt(o.role==='charger'?(o.dashing?'突撃！':'突撃兵'):'砲撃兵',p.x,p.y-74*s,Math.max(11,14*s),o.role==='charger'?'#ffd39b':'#ffb1cc');}
}
else if(o.type==='boss'){if(o.warn)threatLane(o.aim,rel,'#ff5678','砲撃注意');let w=66*s;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#00102050';ctx.beginPath();ctx.ellipse(0,4*s,55*s,14*s,0,0,7);ctx.fill();for(let side of [-1,1]){round(side*22*s-9*s,-27*s,18*s,30*s,4*s,'#28323c');round(side*44*s-9*s,-65*s,18*s,44*s,5*s,'#b34957');ctx.fillStyle='#ebbe7b';ctx.fillRect(side*44*s-4*s,-28*s,8*s,8*s)}round(-w/2,-80*s,w,58*s,12*s,o.hit>0?'#ffe6d2':'#813b50','#d7777f');round(-17*s,-104*s,34*s,28*s,8*s,'#b14e5b');round(-12*s,-92*s,24*s,7*s,2*s,'#ffe2a0');ctx.fillStyle='#182f3c';ctx.beginPath();ctx.arc(0,-48*s,17*s,0,7);ctx.fill();ctx.fillStyle='#ffb07b';ctx.beginPath();ctx.arc(0,-48*s,9*s,0,7);ctx.fill();ctx.restore();let bw=110*s;round(p.x-bw/2,p.y-130*s,bw,10*s,5*s,'#263749');round(p.x-bw/2,p.y-130*s,bw*Math.max(0,o.hp/o.maxHp),10*s,5*s,'#ff8f87');txt(Math.ceil(o.hp),p.x,p.y-146*s,Math.max(12,20*s));}
else if(o.type==='hazard'){ctx.save();ctx.strokeStyle='#fff0e1';ctx.lineWidth=2;ctx.fillStyle='#f34765';ctx.beginPath();ctx.arc(p.x,p.y-12*s,Math.max(6,11*s),0,7);ctx.fill();ctx.stroke();ctx.fillStyle='#ffe6b4';ctx.beginPath();ctx.arc(p.x,p.y-12*s,Math.max(2,4*s),0,7);ctx.fill();ctx.strokeStyle='#ff536477';ctx.lineWidth=6*s;ctx.beginPath();ctx.moveTo(p.x,p.y-25*s);ctx.lineTo(p.x,p.y-45*s);ctx.stroke();ctx.restore()}}

function drawArmy(){let n=state==='menu'?42:army;if(n<=0)return;let visible=Math.min(n,40),cols=Math.ceil(Math.sqrt(visible*1.2));let scale=clamp(W/420,.7,1.25);for(let i=0;i<visible;i++){let row=Math.floor(i/cols),col=i%cols,cnt=Math.min(cols,visible-row*cols);let x=W/2+px*W*.43+(col-(cnt-1)/2)*13*scale+(row%2?2:0),y=H*.74+row*9*scale;unit(x,y,scale*.95,weapon==='pierce'?'#648cea':weapon==='blast'?'#c29552':'#399feb',i*.7)}if(support>0&&state!=='menu'){let x=W/2+px*W*.43,y=H*.74-6;round(x-16,y-18,32,22,5,'#be965a','#ffe0a0');round(x-6,y-40,12,30,3,'#ddc18b');let charge=1-clamp(supportClock/2,0,1);round(x-20,y+10,40,4,2,'#22394c');round(x-20,y+10,40*charge,4,2,'#ffda86');}if(state==='playing'||state==='paused'){let x=W/2+px*W*.43,y=H*.74+Math.ceil(visible/cols)*9*scale+23;round(x-28,y-12,56,26,13,'#102d43e6','#79d8f9');txt(army,x,y+1,17,'#c5f6ff')}}
function draw(dt){battleAudio.tick(state==='playing',rush>0);if(state!=='paused')frameTime+=state==='choice'?0:dt;ctx.save();ctx.clearRect(0,0,W,H);if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake=Math.max(0,shake-dt*30)}background();objects.slice().sort((a,b)=>b.z-a.z).forEach(drawObject);if(state==='menu'){for(let i=0;i<3;i++)drawObject({type:'gate',z:distance+55,x:LANES[i],value:[-8,12,5][i],hit:0});drawObject({type:'boss',z:distance+85,x:0,hp:1800,maxHp:1800})}let visibleBullet=0;for(const b of bullets){if(++visibleBullet%7!==0&&b.kind!=='blast'&&!b.awakening)continue;let p=project(b.x,b.z),q=project(b.x,b.z-(b.awakening?9:5));ctx.lineWidth=(b.awakening?7:b.kind==='pierce'?2.2:b.kind==='blast'?4:1.3)*p.s;ctx.strokeStyle=b.color||'#c4ffff';ctx.lineCap='round';ctx.beginPath();ctx.moveTo(p.x,p.y-14*p.s);ctx.lineTo(q.x,q.y-14*q.s);ctx.stroke();if(b.kind==='blast'){ctx.fillStyle='#fff1b9';ctx.beginPath();ctx.arc(p.x,p.y-14*p.s,3*p.s,0,7);ctx.fill();}}drawArmy();if(muzzle>0&&state==='playing'){let p=project(px,1);ctx.globalAlpha=muzzle/.065;ctx.fillStyle=WEAPONS[weapon].color;ctx.beginPath();ctx.ellipse(p.x,p.y-12,7+Math.min(army,100)*.12,4,0,0,7);ctx.fill();ctx.globalAlpha=1;}for(const r of rings){let q=project(r.x,r.z);ctx.globalAlpha=Math.max(0,r.life/r.max);ctx.strokeStyle=r.color;ctx.lineWidth=3*q.s;ctx.beginPath();ctx.ellipse(q.x,q.y,Math.max(1,(1-r.life/r.max)*65*q.s),Math.max(1,(1-r.life/r.max)*25*q.s),0,0,7);ctx.stroke();if(state!=='paused')r.life-=dt;}ctx.globalAlpha=1;rings=rings.filter(r=>r.life>0);if(state!=='paused'&&state!=='choice'){for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.y+=p.vy*dt;p.vy-=dt*90}for(const f of floats)f.life-=dt}for(const p of particles){let q=project(p.x,p.z);ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(q.x,q.y-p.y,4*q.s,4*q.s)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);for(const f of floats){let p=project(f.x,f.z);ctx.globalAlpha=Math.min(1,f.life*2);txt(f.text,p.x,p.y-50-(1.2-f.life)*45,28,f.color)}ctx.globalAlpha=1;floats=floats.filter(f=>f.life>0);if(flash>0){ctx.fillStyle='#ff44552b';ctx.fillRect(0,0,W,H);flash-=dt}ctx.restore();if(state!=='paused'&&toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0}}
let last=0;function loop(now){let dt=Math.min(.033,(now-last)/1000||.016);last=now;update(dt);draw(dt);requestAnimationFrame(loop)}home();requestAnimationFrame(loop);
// Read-only status for assistive agents; gameplay uses the same state as the UI.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_game_status',title:'ゲーム状況を確認',description:'現在の作戦、部隊人数、到達距離とプレイ状態を読み取る',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({state,level,army,maxArmy,kills,wide,piercing,support,rush,rushCharge,rushCount,bestCombo,score,distance:Math.floor(distance)})})).catch(()=>{})}catch{}}

$('level').onchange=()=>selectStage(Number($('level').value));
selectStage(unlocked());
