import {withTacticalRules} from './enemy-rules.js';
import {openingMissions} from './opening-missions.js';
import {STAGES as BASE} from './stages-v19.js';
export const LEGACY_STAGES=structuredClone(BASE);
export const AREA_NAMES=['草原前哨地','海岸防衛線','砂漠の道','市街地','工業地帯','港湾輸送路','雪山の峠','補給都市','峡谷要塞','雪山司令部'];
const names=['偵察突破','左右の進路','救援をつなげ','交差する列','守りを崩せ','追撃をかわす','増援の道','最後の障害','前線を押せ','司令部突破'];
const copy=x=>structuredClone(x);
function generateBaselineCampaign(){return Array.from({length:100},(_,index)=>{const area=Math.floor(index/10),step=index%10+1,base=copy(BASE[area]),milestone=step===10;if(!milestone){const mirror=[2,5,8].includes(step)?-1:1,time=.72+step*.023;base.objects=base.objects.filter((o,i)=>!o.boss&&!o.escort&&!o.lateRescue&&(o.type!=='enemy'||o.role!=='guard'||(i+step)%4!==0)).map(o=>{o.x*=mirror;if(o.d>10)o.d*=.70+step*.016;if(o.spawnAt)o.spawnAt*=time;if(o.type==='enemy'){o.hp=Math.max(3,Math.round(o.hp*(.55+step*.04)));if(o.approach)o.approach*=.9+step*.008;}return o;});const final=base.objects.filter(o=>o.type==='gate').sort((a,b)=>b.d-a.d)[0];final.d=48+step*1.5;final.value=8+area*2+step;final.prebossSupply=true;const at=final.d/2.7+2;for(let i=0;i<8+step;i++)base.objects.push({type:'enemy',role:i%5===0?'weaver':'guard',d:0,x:((i%5)-2)*1.25,hp:i%5===0?7:4,spawnAt:at+(i%2)*.4,spawnZ:-12-Math.floor(i/5)*1.2,approach:6.4});base.durationHint=at+7;}return{...base,id:'c'+String(index+1).padStart(3,'0'),name:names[step-1],areaName:AREA_NAMES[area],area,bandIndex:area,step,milestone,band:`${AREA_NAMES[area]} · ${step}/10`,startForce:3,tip:milestone?base.tip:'増援板を育て、空いた列から敵を狙おう。'};});}
const V20_STAGES=generateBaselineCampaign();
export function generateCampaign(){return openingMissions(V20_STAGES).map(withTacticalRules);}
export const STAGES=generateCampaign();
export const DAILY_NAMES=['大軍の救援','装甲突破','障害帯を抜けろ'];
export function dailyStage(day,slot){let seed=2166136261;for(const c of day+':'+slot)seed=Math.imul(seed^c.charCodeAt(0),16777619)>>>0;const base=copy(V20_STAGES[[0,20,10][slot]+1+(seed>>>4)%6]),mirror=seed%2?-1:1;base.objects=base.objects.filter(o=>o.type!=='spikes'||slot===2).map(o=>({...o,x:o.x*mirror}));if(slot===0){for(const o of base.objects)if(o.type==='gate'&&o.d>20)o.value=Math.max(20,o.value);for(const o of base.objects)if(o.type==='rescue')o.gain=18;}if(slot===1)for(let i=0;i<3;i++)base.objects.push({type:'enemy',d:0,x:i%2?1.7:-1.7,hp:32,role:'shield',spawnAt:7+i*4,spawnZ:-19,approach:5.2});if(slot===2)for(let i=0;i<3;i++)base.objects.push({type:'spikes',d:32+i*12,x:(i%2?2.45:-2.45)*mirror});return withTacticalRules({...base,id:`daily:${day}:${slot}`,name:DAILY_NAMES[slot],band:'特別作戦 · '+(slot+1)+'/3',dailyDay:day,dailySlot:slot,seed,kind:'daily',startForce:3,milestone:false});}
