'use strict';
// Lightweight cutout rig: legs pivot separately under an overlapping torso.
let motionTime=0,motionActor=null,motionFalls=[],motionRun=-1;
const stillUnit=unit,stillObject=drawObject,stillAtlas=atlas,stillDraw=draw,stillHit=hitEnemy;
function rig(sheet,index,x,y,w,h,pose){if(!sheet?.complete||!sheet.naturalWidth)return false;const cw=sheet.naturalWidth/2,ch=sheet.naturalHeight/2,sx=index%2*cw,sy=Math.floor(index/2)*ch,hip=.60,step=pose.step,weight=Math.abs(step);ctx.save();ctx.translate(x,y);ctx.rotate(pose.lean);ctx.scale(1,pose.squash||1);
// The ground stays fixed. Alternate planted and advancing feet, rather than moving the entire sprite vertically.
for(let side=0;side<2;side++){let sign=side?1:-1,legStep=step*sign,anchor=(side? .12:-.12)*w;ctx.save();ctx.translate(anchor,-h*(1-hip));ctx.rotate(legStep*pose.stride);ctx.translate(0,-Math.max(0,legStep)*h*.035);ctx.drawImage(sheet,sx+side*cw/2,sy+ch*hip,cw/2,ch*(1-hip),-w/2+side*w/2-anchor,-h*.015,w/2,h*(1-hip)+h*.015);ctx.restore();}
// Chest counter-rotates against the hips; recoil belongs to the upper body.
ctx.save();ctx.translate(0,-h*(1-hip));ctx.rotate(-step*pose.stride*.22+pose.recoil*.04);ctx.translate(0,pose.recoil*h*.025-weight*h*.008);ctx.drawImage(sheet,sx,sy,cw,ch*.64,-w/2,-h*hip,w,h*.64);ctx.restore();ctx.restore();return true;}
function poseFor(o,phase=0,heavy=false){const boss=o?.type==='boss',charging=o?.role==='charger',mortar=o?.role==='mortar',rel=o?o.z-distance:0;let walking=!o||(!mortar&&!(charging&&o.aim!==null&&!o.dashing)&&(!boss||rel>24));let speed=o?.dashing?21:boss?4.2:heavy?8.5:12;let step=walking?Math.sin(motionTime*speed+phase):Math.sin(motionTime*2+phase)*.08;let recoil=o?Math.max(0,(o.hit||0)/.09):clamp(muzzle/.05,0,1);let lean=o?clamp((o.x-px)*-.055,-.06,.06):clamp((targetX-px)*-.45,-.16,.16);let squash=1,stride=boss?.07:walking?.19:.025;if(charging&&o.aim!==null){if(o.dashing){lean+=.16;stride=.3;}else{squash=1-clamp(o.wind/1.05,0,1)*.13;lean-=.09;}}if(mortar&&o.warn){squash=.94;lean-=.04;}if(boss&&o.warn){squash=.97;lean+=Math.sin(motionTime*17)*.006;}return {step,stride,lean:lean-recoil*.05,recoil,squash};}
unit=function(x,y,s,color='#42a9ef',phase=0,heavy=false){const special=heavy&&(color==='#f69b43'||color==='#d55483'),sheet=special?spriteSheet:premiumAtlas,index=special?(color==='#f69b43'?2:3):heavy?1:0;ctx.fillStyle='#02101d55';ctx.beginPath();ctx.ellipse(x+2*s,y,11*s,4*s,0,0,7);ctx.fill();if(!rig(sheet,index,x,y+3*s,(special?42:52)*s,(special?42:52)*s,poseFor(motionActor,phase,heavy)))stillUnit(x,y,s,color,phase,heavy);};
atlas=function(index,x,y,w,h){if(index!==2)return stillAtlas(index,x,y,w,h);return rig(premiumAtlas,index,x,y,w,h,poseFor(motionActor,motionActor?.phase||0,true));};
drawObject=function(o){motionActor=o;if(o.type==='enemy'&&o.dashing){let p=project(o.x,o.z-distance);ctx.save();ctx.strokeStyle='#ffba6560';ctx.lineWidth=2*p.s;for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(p.x+i*15*p.s,p.y-8*p.s);ctx.lineTo(p.x+i*18*p.s,p.y-45*p.s);ctx.stroke();}ctx.restore();}try{stillObject(o)}finally{motionActor=null}};
hitEnemy=function(o,damage){const alive=!o.dead;stillHit(o,damage);if(alive&&o.dead&&o.type==='enemy'){motionFalls.push({x:o.x,z:o.z,role:o.role,phase:o.phase,t:0,dir:o.x>=px?1:-1});if(motionFalls.length>22)motionFalls.shift();}};
draw=function(dt){if(elapsed<motionRun){motionFalls=[];motionTime=0;}motionRun=elapsed;if(state==='playing')motionTime+=dt;stillDraw(dt);if(state==='menu'){motionFalls=[];return;}for(const f of motionFalls){if(state!=='paused')f.t+=dt;const rel=f.z-distance;if(rel<0||rel>110)continue;const p=project(f.x,rel),special=!!f.role,sheet=special?spriteSheet:premiumAtlas,index=f.role==='charger'?2:f.role==='mortar'?3:1;ctx.save();ctx.globalAlpha=Math.max(0,1-f.t/.32)*.65;ctx.translate(p.x,p.y);ctx.rotate(f.dir*Math.min(1,f.t*4));ctx.scale(1,Math.max(.35,1-f.t*2));rig(sheet,index,0,0,(special?65:62)*p.s,(special?65:62)*p.s,{step:0,stride:0,lean:0,recoil:0,squash:1});ctx.restore();}motionFalls=motionFalls.filter(f=>f.t<.32);};
