'use strict';
const premiumAtlas=typeof Image!=='undefined'?new Image():null,canyonArt=typeof Image!=='undefined'?new Image():null;
if(premiumAtlas)premiumAtlas.src='assets/units-premium.png';if(canyonArt)canyonArt.src='assets/canyon-premium.png';
const originalUnit=unit,originalObject=drawObject,originalDraw=draw;let celebrationTime=0,previousVisualState='menu';
function atlas(index,x,y,w,h){if(!premiumAtlas?.complete||!premiumAtlas.naturalWidth)return false;let cw=premiumAtlas.naturalWidth/2,ch=premiumAtlas.naturalHeight/2;ctx.drawImage(premiumAtlas,index%2*cw,Math.floor(index/2)*ch,cw,ch,x-w/2,y-h,w,h);return true;}
unit=function(x,y,s,color='#42a9ef',phase=0,heavy=false){if(heavy&&(color==='#f69b43'||color==='#d55483'))return originalUnit(x,y,s,color,phase,heavy);ctx.fillStyle='#02101d55';ctx.beginPath();ctx.ellipse(x+3*s,y,11*s,4*s,0,0,7);ctx.fill();let bob=state==='playing'?Math.sin(frameTime*11+phase)*1.3*s:0;if(!atlas(heavy?1:0,x,y+3*s+bob,52*s,52*s))originalUnit(x,y,s,color,phase,heavy);};
background=function(){ctx.fillStyle='#173044';ctx.fillRect(0,0,W,H);if(canyonArt?.complete&&canyonArt.naturalWidth){const scale=Math.max(W/canyonArt.naturalWidth,H/canyonArt.naturalHeight),iw=canyonArt.naturalWidth*scale,ih=canyonArt.naturalHeight*scale;ctx.drawImage(canyonArt,(W-iw)/2,(H-ih)/2,iw,ih);}if(level>=4){ctx.fillStyle=level>=8?'#121c5650':'#082b4528';ctx.fillRect(0,0,W,H);}const top=project(-1,110),top2=project(1,110);let road=ctx.createLinearGradient(0,H*.23,0,H);road.addColorStop(0,'#768c92');road.addColorStop(.45,'#3c5461');road.addColorStop(1,'#1b303e');poly([[top.x,top.y],[top2.x,top2.y],[W*.98,H],[W*.02,H]],road);for(let z=-12;z<115;z+=8){let zz=z-distance%8;let a=project(-1,zz),b=project(1,zz),c=project(1,zz+7.5),d=project(-1,zz+7.5);poly([[a.x,a.y],[b.x,b.y],[c.x,c.y],[d.x,d.y]],z%16===0?'#b4c8d010':'#03132118');ctx.strokeStyle='#c1dce526';ctx.lineWidth=Math.max(.5,a.s);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();for(const x of [-.94,.94]){let p=project(x,zz+1);ctx.fillStyle='#afbbc080';ctx.fillRect(p.x,p.y,2*p.s,2*p.s);}for(const x of [-.333,.333]){let p=project(x,zz),q=project(x,zz+3);ctx.strokeStyle='#ccdfda38';ctx.lineWidth=1.5*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}
for(const side of [-1,1]){let a=project(side*1.01,110),b=project(side*1.01,0),c=project(side*1.11,0),d=project(side*1.11,110);poly([[a.x,a.y],[b.x,b.y],[W/2+side*W*.50,H],[W/2+side*W*.55,H],[c.x,c.y],[d.x,d.y]],'#112434');ctx.strokeStyle='#78939e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(W/2+side*W*.50,H);ctx.stroke();for(let z=0;z<112;z+=8){let p=project(side*1.035,z-distance%8),q=project(side*1.035,z-distance%8+3);ctx.strokeStyle=side<0?'#ffd28b':'#83eaff';ctx.lineWidth=4*p.s;ctx.beginPath();ctx.moveTo(p.x,p.y-5*p.s);ctx.lineTo(q.x,q.y-5*q.s);ctx.stroke();}}
const fade=ctx.createLinearGradient(0,H*.72,0,H);fade.addColorStop(0,'#07162600');fade.addColorStop(1,'#071626e8');ctx.fillStyle=fade;ctx.fillRect(0,H*.72,W,H*.28);
};
drawObject=function(o){let rel=o.z-distance;if(rel>110||rel<-.5)return;let p=project(o.x,rel),s=p.s;
if(o.type==='boss'&&premiumAtlas?.naturalWidth){if(o.warn)threatLane(o.aim,rel,'#ff5470','砲撃注意');ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(p.x,p.y,65*s,15*s,0,0,7);ctx.fill();atlas(2,p.x,p.y+6*s,165*s,165*s);if(o.hit>0){ctx.fillStyle='#ffe4a755';ctx.beginPath();ctx.arc(p.x,p.y-80*s,10*s,0,7);ctx.fill();}let bw=126*s;round(p.x-bw/2,p.y-173*s,bw,7*s,3*s,'#081725','#ffc5a455');round(p.x-bw/2,p.y-173*s,bw*clamp(o.hp/o.maxHp,0,1),7*s,3*s,'#ff8668');txt('TITAN / '+Math.ceil(o.hp),p.x,p.y-188*s,Math.max(10,12*s),'#ffe3c3');return;}
if(o.type==='crate'&&premiumAtlas?.naturalWidth){atlas(3,p.x,p.y+4*s,64*s,64*s);round(p.x-24*s,p.y-75*s,48*s,19*s,4*s,'#102b3b');txt('+'+o.reward,p.x,p.y-65*s,Math.max(11,15*s),'#a4ffec');return;}
if(o.type==='gate'){let w=W*.255*s,h=48*s,positive=o.value>=0,color=positive?'#52d8fa':'#ff637d';ctx.fillStyle='#04121b66';ctx.beginPath();ctx.ellipse(p.x,p.y+3*s,w*.55,8*s,0,0,7);ctx.fill();let glass=ctx.createLinearGradient(0,p.y-h,0,p.y);glass.addColorStop(0,positive?'#277d9ff0':'#aa405df0');glass.addColorStop(1,positive?'#113e61eb':'#4b263feb');round(p.x-w/2,p.y-h,w,h,5*s,glass,color);ctx.fillStyle='#ffffff13';ctx.fillRect(p.x-w/2+4*s,p.y-h+5*s,w-8*s,10*s);for(let side of [-1,1]){round(p.x+side*w/2-3*s,p.y-h-3*s,6*s,h+8*s,2*s,'#18344a','#9ab8c5');ctx.fillStyle=color;ctx.fillRect(p.x+side*w/2-1*s,p.y-h+2*s,2*s,h-2*s);}ctx.fillStyle=color;ctx.fillRect(p.x-w/2+4*s,p.y-3*s,(w-8*s)*clamp(o.progress/gateThreshold(o.value),0,1),2*s);txt((positive?'+':'')+o.value,p.x,p.y-h*.5,Math.max(12,Math.min(30*s,w/((String(o.value).length+1)*.66))),o.hit>0?'#fff':'#e9faff');return;}
originalObject(o);
};
draw=function(dt){originalDraw(dt);if(state==='won'&&previousVisualState!=='won')celebrationTime=0;previousVisualState=state;if(state==='won'){celebrationTime+=dt;if(celebrationTime<3){ctx.save();for(let i=0;i<45;i++){let t=celebrationTime,x=(i*83.7%W)+Math.sin(t*2+i)*30,y=(i*47%H*.55)+t*(50+i%7*14);ctx.globalAlpha=Math.max(0,1-t/3);ctx.fillStyle=i%2?'#ffdc8a':'#92e6ff';ctx.save();ctx.translate(x,y);ctx.rotate(i+t*2);ctx.fillRect(-2,-4,4,8);ctx.restore();}ctx.restore();}}};
$('app').classList.add('premium');
// Fewer, larger visible soldiers keep the squad readable; the counter is the full force.
drawArmy=function(){let n=state==='menu'?30:army;if(n<=0)return;let visible=Math.min(n,30),cols=Math.ceil(Math.sqrt(visible*1.2)),scale=clamp(W/420,.75,1.2);for(let i=0;i<visible;i++){let row=Math.floor(i/cols),col=i%cols,cnt=Math.min(cols,visible-row*cols);let x=W/2+px*W*.43+(col-(cnt-1)/2)*19*scale+(row%2?3:0),y=H*.74+row*12*scale;unit(x,y,scale*1.18,'#399feb',i*.7);}if(support>0&&state!=='menu'){let x=W/2+px*W*.43,y=H*.74-9;round(x-16,y-18,32,22,5,'#947343','#ffe0a0');round(x-6,y-40,12,30,3,'#d9bd8b');round(x-20,y+10,40,3,2,'#172b3d');round(x-20,y+10,40*(1-clamp(supportClock/2,0,1)),3,2,'#ffda86');}if(state==='playing'||state==='paused'){let x=W/2+px*W*.43,y=H*.74+Math.ceil(visible/cols)*12*scale+18;round(x-25,y-11,50,23,11,'#081d2de6','#74cae280');txt(army,x,y+1,16,'#d5faff');}};
const premiumFinish=finish;finish=function(win){premiumFinish(win);$('result').classList.toggle('defeat',!win);};
