'use strict';
// A finite application layer: three exercises, one selected relic, no campaign penalties.
const EXERCISES={
 breach:{level:8,name:'破盾演習',goal:'中継塔2基を破壊して突破',hint:'照準を塔へ保つ時間と、砲撃から離れる瞬間を選ぼう。',recommend:'lance',color:'#8adfff'},
 sweep:{level:9,name:'掃討演習',goal:'90%以上撃破・被害12人以内で突破',hint:'密集には連鎖と榴弾。突撃の予告では横へ離れよう。',recommend:'volt',color:'#9df0d7',ratio:.9,damage:12},
 rescue:{level:10,name:'救難演習',goal:'救難機3機を回収して突破',hint:'救出を選ぶと武装を逃す。コイルで補うか、ドローンで守るか。',recommend:'swarm',color:'#ffd491'}
};
let exerciseRequest=null,exerciseStarting=false,exerciseResult=null,exerciseSelection={id:'breach',machine:'lance',gear:'prism'};
function exerciseContext(){return exerciseStarting?exerciseRequest:expeditionRun?.exercise||null;}
function reinforcementCap(){return exerciseContext()?12:24;}
function activeRunRelics(){const e=exerciseContext();return e?(e.gear==='none'?[]:[e.gear]):arsenal.installed||[];}
function exercisesUnlocked(){return !!campaign.records[10];}
function exerciseName(gear){return gear==='none'?'装備なし':RELICS[gear]?.short||'装備なし';}
function exerciseMedals(){return Object.keys(EXERCISES).filter(id=>campaign.tactics?.records?.[id]?.medal).length;}
function medalSVG(id,earned=true){const color=EXERCISES[id]?.color||'#ffe3a0',symbol={breach:'Ⅱ',sweep:'ϟ',rescue:'✦'}[id]||'★';return '<svg viewBox="0 0 100 100" class="tactic-medal '+(earned?'earned':'')+'" aria-hidden="true"><path d="M26 5 H43 L50 35 35 45 Z M57 5 H74 L65 45 50 35 Z" fill="#5e7891"/><path d="M50 24 L78 40 78 72 50 89 22 72 22 40 Z" fill="#183347" stroke="'+color+'" stroke-width="5"/><path d="M50 31 L71 44 V68 L50 81 29 68 V44 Z" fill="none" stroke="'+color+'"/><text x="50" y="66" text-anchor="middle" font-size="35" fill="'+color+'">'+symbol+'</text></svg>';}
const tacticsPanel=document.createElement('section');tacticsPanel.id='tacticsPanel';tacticsPanel.className='overlay hidden';tacticsPanel.setAttribute('aria-labelledby','tacticsTitle');$('app').append(tacticsPanel);
const tacticsResultPanel=document.createElement('section');tacticsResultPanel.id='tacticsResult';tacticsResultPanel.className='overlay hidden';tacticsResultPanel.setAttribute('aria-labelledby','tacticsResultTitle');$('app').append(tacticsResultPanel);
const tacticsEntry=document.createElement('button');tacticsEntry.id='tacticsEntry';tacticsEntry.className='secondary';$('stageGrid').before(tacticsEntry);tacticsEntry.onclick=()=>openTactics();
function renderTacticsEntry(){const ready=exercisesUnlocked();tacticsEntry.disabled=!ready;tacticsEntry.textContent=ready?'応用 / 戦術演習  '+exerciseMedals()+' / 3 達成':'作戦10クリアで戦術演習を解放';}
function openTactics(){if(!exercisesUnlocked())return;if(['playing','paused'].includes(state)&&!$('missionBrief').classList.contains('hidden'))return;clearExpeditionPresentation();tacticsResultPanel.classList.add('hidden');$('hangar').classList.add('hidden');renderTactics();tacticsPanel.classList.remove('hidden');}
function renderTactics(){const count=exerciseMedals();tacticsPanel.innerHTML='<div class="stage-header"><div><span class="eyebrow">APPLICATION / 3 EXERCISES</span><h2 id="tacticsTitle">戦術演習</h2></div><button class="textbutton" id="closeTactics">戻る</button></div><p class="tactics-intro">覚えた戦術を、別の組み合わせで。<br>演習だけ：装備1種・増援ゲート最大 +12</p><div class="tactics-collection">'+Object.keys(EXERCISES).map(id=>medalSVG(id,!!campaign.tactics?.records?.[id]?.medal)).join('')+'<p>'+count+' / 3 勲章'+(count===3?' · 記念装飾を獲得':'<br>3つ揃えると機体・格納庫に記念装飾')+'</p></div><div id="exerciseCards">'+Object.entries(EXERCISES).map(([id,m])=>{const record=campaign.tactics?.records?.[id];return '<article class="exercise-card"><span>作戦 '+m.level+' を応用</span><h3>'+m.name+(record?.medal?' ✓':'')+'</h3><p>'+m.goal+'</p><p class="tactics-hint">'+m.hint+'</p><button class="secondary" data-exercise="'+id+'">機体と装備を選ぶ</button>'+exerciseHistory(id)+'</article>';}).join('')+'</div>';$('closeTactics').onclick=()=>tacticsPanel.classList.add('hidden');$('exerciseCards').onclick=e=>{const id=e.target.closest('[data-exercise]')?.dataset.exercise;if(id)prepareExercise(id);};}
function exerciseHistory(id){const rows=Object.values(campaign.tactics?.records?.[id]?.loadouts||{});if(!rows.length)return '<small>まだ記録がありません</small>';return '<details><summary>機体・装備別の記録 ('+rows.length+')</summary>'+rows.map(r=>'<p class="exercise-history"><b>'+MACHINES.find(m=>m.id===r.last.machine).name+' × '+exerciseName(r.last.gear)+'</b><span>最高：'+exerciseMetric(id,r.best)+' / '+(r.best.achieved?'達成':'未達')+'</span><span>前回：'+exerciseMetric(id,r.last)+' / '+r.attempts+'回挑戦</span></p>').join('')+'</details>';}
function exerciseMetric(id,r){return id==='breach'?'塔 '+r.relays+'/2 · 被害 '+r.damage+'人':id==='sweep'?'撃破 '+Math.floor(r.kills/r.total*100)+'% · 被害 '+r.damage+'人':'救出 '+r.rescued+'/3 · 残兵 '+r.army;}
function prepareExercise(id,retain=false){if(!exercisesUnlocked()||!EXERCISES[id])return;const m=EXERCISES[id];if(!retain)exerciseSelection={id,machine:m.recommend,gear:relicOwned('prism')?'prism':relicOwned('guardian')?'guardian':'none'};exerciseSelection.id=id;tacticsPanel.innerHTML='<div class="stage-header"><div><span class="eyebrow">LOADOUT / '+m.name+'</span><h2 id="tacticsTitle">今回の組み合わせ</h2></div><button class="textbutton" id="backExercises">戻る</button></div><p class="exercise-goal">'+m.goal+'</p><h3>機体を選ぶ</h3><div class="tactic-machines">'+MACHINES.map(machine=>'<button data-tactic-machine="'+machine.id+'" aria-pressed="'+(exerciseSelection.machine===machine.id)+'">'+machineSVG(machine.id,exerciseSelection.gear==='none'?[]:[exerciseSelection.gear])+'<b>'+machine.name+'</b><small>'+machine.tag+(arsenal.owned.includes(machine.id)?'':' / 無料試乗')+'</small></button>').join('')+'</div><h3>装備を1種選ぶ</h3><div class="tactic-gears">'+['prism','guardian','none'].filter(id=>id==='none'||relicOwned(id)).map(gear=>'<button data-tactic-gear="'+gear+'" aria-pressed="'+(exerciseSelection.gear===gear)+'">'+(gear==='none'?'<span class="no-gear">—</span>':relicSVG(gear))+'<b>'+exerciseName(gear)+'</b></button>').join('')+'</div><p class="gear-explanation">'+(RELICS[exerciseSelection.gear]?.detail||'追加の効果なし。装備は作戦5・10のクリアで獲得できます。')+'</p><p class="tactics-hint">初期部隊12人 / ゲート最大 +12<br>通常作戦の装備・増援は変わりません</p><button class="primary" id="launchExercise">この組み合わせで挑戦</button><p class="tactics-hint" id="exerciseLaunchNotice"></p>';
 $('backExercises').onclick=renderTactics;tacticsPanel.querySelector('.tactic-machines').onclick=e=>{const id=e.target.closest('[data-tactic-machine]')?.dataset.tacticMachine;if(id){exerciseSelection.machine=id;prepareExercise(exerciseSelection.id,true);}};tacticsPanel.querySelector('.tactic-gears').onclick=e=>{const id=e.target.closest('[data-tactic-gear]')?.dataset.tacticGear;if(id){exerciseSelection.gear=id;prepareExercise(exerciseSelection.id,true);}};$('launchExercise').onclick=()=>{if(checkpointData.run){$('exerciseLaunchNotice').innerHTML='中断中の戦闘があります。<button class="textbutton" id="resumeExistingExercise">つづきから</button><button class="textbutton" id="replaceExistingExercise">中断を終了して、この演習へ</button>';$('resumeExistingExercise').onclick=()=>{tacticsPanel.classList.add('hidden');showRecovery();};$('replaceExistingExercise').onclick=()=>launchExercise(exerciseSelection);return;}launchExercise(exerciseSelection);};
}
function launchExercise(selection){if(!exercisesUnlocked())return;const m=EXERCISES[selection.id];if(!m)return;const gear=relicOwned(selection.gear)?selection.gear:'none';exerciseRequest={id:selection.id,gear,version:1};chosenMachine=selection.machine;tacticsPanel.classList.add('hidden');tacticsResultPanel.classList.add('hidden');start(m.level,true);}
const normalRelicInstalled=relicInstalled;
relicInstalled=id=>{const e=exerciseContext();return e?e.gear===id&&relicOwned(id):normalRelicInstalled(id);};
const tacticalMakeLevel=makeLevel;
makeLevel=function(){tacticalMakeLevel();if(!exerciseContext())return;for(const o of objects)if(o.type==='gate'){o.cap=12;o.value=Math.min(o.value,12);}};
const tacticalGateThreshold=gateThreshold;
gateThreshold=function(value){return exerciseContext()?(value>=12?Infinity:8+Math.max(0,value-8)*1.4):tacticalGateThreshold(value);};
const tacticalStart=start;
start=function(n=level){exerciseResult=null;tacticsResultPanel.classList.add('hidden');exerciseStarting=true;try{tacticalStart(n);if(exerciseRequest)expeditionRun.exercise={...exerciseRequest};}finally{exerciseStarting=false;exerciseRequest=null;}if(exerciseContext())$('stageName').textContent=EXERCISES[exerciseContext().id].name;};
const tacticalBriefing=missionBriefing;
missionBriefing=function(){tacticalBriefing();const e=exerciseContext();if(!e)return;const m=EXERCISES[e.id];missionBrief.querySelector('.brief-hero').innerHTML=machineSVG(runMachine.id,e.gear==='none'?[]:[e.gear]);$('missionTitle').textContent=m.name;missionBrief.querySelector('.eyebrow').textContent='APPLICATION / 応用';missionBrief.querySelector('.brief-goal').textContent=m.goal;missionBrief.querySelector('.brief-goal').nextElementSibling.textContent=m.hint;missionBrief.querySelector('.brief-tools').innerHTML='<span>装備1種：'+exerciseName(e.gear)+'</span><span>増援ゲート最大 +12</span>';missionBrief.querySelector('.brief-equipped').textContent='勲章は条件達成時に獲得。機体・装備別に記録します。';$('briefMachineSwitch')?.remove();};
const tacticalRestore=restoreExpedition;
restoreExpedition=function(saved){tacticsPanel.classList.add('hidden');tacticsResultPanel.classList.add('hidden');exerciseResult=null;tacticalRestore(saved);if(exerciseContext())$('stageName').textContent=EXERCISES[exerciseContext().id].name;};
const tacticalHud=updateMissionHud;
updateMissionHud=function(){tacticalHud();const e=exerciseContext();if(!e||!['playing','paused'].includes(state))return;const m=EXERCISES[e.id],detail=e.id==='breach'?'塔 '+expeditionRun.relays+'/2':e.id==='rescue'?'救出 '+expeditionRun.rescued+'/3':'撃破 '+kills+'/'+Math.ceil(totalEnemies*m.ratio)+' · 被害 '+damageTaken+'/'+m.damage;missionHud.innerHTML='<b>'+m.name+'</b><span>'+detail+'</span>';};
function exerciseAssessment(win,e){const m=EXERCISES[e.id],r={win,machine:runMachine.id,gear:e.gear,relays:expeditionRun.relays,rescued:expeditionRun.rescued,kills,total:totalEnemies,damage:damageTaken,army,score,time:elapsed};r.achieved=win&&(e.id==='breach'?r.relays>=2:e.id==='rescue'?r.rescued>=3:r.kills>=Math.ceil(r.total*m.ratio)&&r.damage<=m.damage);return r;}
function exerciseMerit(id,r){return (r.achieved?1e8:0)+(r.win?1e6:0)+(id==='breach'?r.relays*10000:id==='rescue'?r.rescued*10000:r.kills*1000)-r.damage*10+r.army;}
function exerciseAdvice(id,r){const m=EXERCISES[id],lines=[];if(!r.win)lines.push('まずは要塞突破。'+(lastDamage||'増援を確保し、予告から横へ離れよう。'));if(id==='breach'&&r.relays<2)lines.push('塔あと'+(2-r.relays)+'基。貫通を選び、塔の正面を長めに狙おう。');if(id==='rescue'&&r.rescued<3)lines.push('救出あと'+(3-r.rescued)+'機。左の金色信号へ、砲撃の後に戻ろう。');if(id==='sweep'){const missing=Math.max(0,Math.ceil(r.total*m.ratio)-r.kills),excess=Math.max(0,r.damage-m.damage);if(missing)lines.push('撃破あと'+missing+'体。ワイド・榴弾で左右の撃ち残しを減らそう。');if(excess)lines.push('被害をあと'+excess+'人減らそう。突撃は横へ回避。ドローンも選べます。');}return lines.length?lines.join('<br>'):'別の機体・装備なら、どこまで被害を減らせる？';}
const tacticalFinish=finish;
finish=function(win){if(state!=='playing')return;const e=exerciseContext();if(!e){tacticalFinish(win);if(win&&[7,8,9].includes(level)&&expeditionRun){campaign.objectives=campaign.objectives||{};const old=campaign.objectives[level]||{};campaign.objectives[level]={relays:Math.max(old.relays||0,expeditionRun.relays),rescued:Math.max(old.rescued||0,expeditionRun.rescued)};refreshCampaign();}return;}
 const r=exerciseAssessment(win,e),before=exerciseMedals();campaign.tactics=campaign.tactics||{records:{},commemorative:false};const records=campaign.tactics.records;const record=records[e.id]||(records[e.id]={medal:false,attempts:0,loadouts:{}}),key=r.machine+'_'+r.gear,old=record.loadouts[key];record.attempts++;record.medal=record.medal||r.achieved;record.loadouts[key]={attempts:(old?.attempts||0)+1,last:r,best:!old||exerciseMerit(e.id,r)>exerciseMerit(e.id,old.best)?r:old.best};campaign.tactics.commemorative=Object.keys(EXERCISES).every(id=>records[id]?.medal);exerciseResult={...r,id:e.id,newMedal:exerciseMedals()>before,newDecoration:before<3&&exerciseMedals()===3};state=win?'won':'lost';drag=false;earnedThisRun=true;missionHud.hidden=true;coach.hidden=true;clearExpeditionPresentation();$('pauseMenu').classList.add('hidden');$('result').classList.add('hidden');$('pause').style.display='none';$('hint').style.display='none';$('rushHud').style.display='none';battleAudio.effect(r.achieved?'win':'lose');commandArtCache.clear();renderHangar();refreshCampaign();showExerciseResult();
};
const tacticalMaterial=resultMaterialEarned;
resultMaterialEarned=function(base){return exerciseResult?0:tacticalMaterial(base);};
function showExerciseResult(){const r=exerciseResult,m=EXERCISES[r.id],best=campaign.tactics.records[r.id].loadouts[r.machine+'_'+r.gear].best;tacticsResultPanel.innerHTML='<span class="eyebrow">'+m.name+' / '+MACHINES.find(x=>x.id===r.machine).name+' × '+exerciseName(r.gear)+'</span>'+medalSVG(r.id,r.achieved)+'<h2 id="tacticsResultTitle">'+(r.achieved?'演習、達成！':r.win?'突破。あと少し。':'組み合わせを変えて、もう一度。')+'</h2><p class="exercise-goal">'+exerciseMetric(r.id,r)+'</p><p class="exercise-advice">'+exerciseAdvice(r.id,r)+'</p><p class="tactics-hint">'+(r.newMedal?'新しい勲章を格納庫に保管しました。':r.achieved?'獲得済みの勲章は保持しています。':'達成済みの記録・勲章は失いません。')+'<br>この組み合わせの最高：'+exerciseMetric(r.id,best)+'</p>'+(r.newDecoration?'<div class="commemorative-reward">'+machineSVG(r.machine,r.gear==='none'?[]:[r.gear])+'<b>3つの勲章が揃った！</b><span>機体と格納庫に「帰還の翼」を装着</span></div>':'')+'<p id="exerciseSaveStatus" class="tactics-hint"></p><button class="primary" id="retryExercise">同じ組み合わせでもう一度</button><button class="secondary" id="changeExerciseLoadout">機体・装備を変える</button><button class="textbutton" id="returnExercises">演習一覧へ</button>';tacticsResultPanel.classList.remove('hidden');tacticsResultPanel.classList.toggle('new-medal',r.newMedal);$('retryExercise').onclick=()=>launchExercise({id:r.id,machine:r.machine,gear:r.gear});$('changeExerciseLoadout').onclick=()=>{exerciseSelection={id:r.id,machine:r.machine,gear:r.gear};tacticsResultPanel.classList.add('hidden');tacticsPanel.classList.remove('hidden');prepareExercise(r.id,true);};$('returnExercises').onclick=openTactics;
 setTimeout(()=>{if($('exerciseSaveStatus'))$('exerciseSaveStatus').textContent=checkpointFailed?'未保存です。画面を閉じず「保存を再試行」を押してください。':'記録と勲章を保存しました。';if(checkpointFailed&&$('exerciseSaveStatus')){const retry=document.createElement('button');retry.className='textbutton';retry.textContent='保存を再試行';retry.onclick=()=>{saveArsenal();if(!checkpointFailed)$('exerciseSaveStatus').textContent='記録と勲章を保存しました。';};$('exerciseSaveStatus').append(retry);}},80);
}
const tacticalMachineSVG=machineSVG;
machineSVG=function(id,installed=[],compact=false){let svg=tacticalMachineSVG(id,installed,compact);if(campaign.tactics?.commemorative)svg=svg.replace('</svg>','<g class="commemorative-wings" fill="#ffe2a0" stroke="#664a21" stroke-width="1"><path d="M43 15 L22 5 25 15 43 24 M77 15 L98 5 95 15 77 24"/><path d="M60 8 L64 15 72 16 66 22 68 30 60 26 52 30 54 22 48 16 56 15 Z"/></g></svg>');return svg;};
const tacticalHangar=renderHangar;
renderHangar=function(){tacticalHangar();let collection=$('hangarMedals');if(!collection){collection=document.createElement('div');collection.id='hangarMedals';$('hangarBay').after(collection);}collection.innerHTML=exercisesUnlocked()?'<div class="tactics-collection">'+Object.keys(EXERCISES).map(id=>medalSVG(id,!!campaign.tactics?.records?.[id]?.medal)).join('')+'<p>'+exerciseMedals()+' / 3 勲章'+(campaign.tactics?.commemorative?' · 帰還の翼 装着中':'')+'</p></div>':'';if(exercisesUnlocked()&&expeditionVictory?.level===10&&$('deployFromHangar')){$('deployFromHangar').textContent='応用 / 戦術演習へ';$('deployFromHangar').onclick=openTactics;}if(exercisesUnlocked()&&!expeditionVictory){const button=document.createElement('button');button.className='secondary';button.textContent='戦術演習へ';button.onclick=openTactics;collection.append(button);}};
const tacticalCampaign=refreshCampaign;
refreshCampaign=function(){tacticalCampaign();renderTacticsEntry();for(const n of[7,8,9]){const record=campaign.objectives?.[n],m=EXPEDITIONS[n],card=$('stageGrid').querySelector('[data-stage="'+n+'"]');if(record&&card){const line=document.createElement('small');line.className='objective-best';line.textContent=m.relayGoal?'最高：塔 '+record.relays+'/'+m.relayGoal:'最高：救出 '+record.rescued+'/'+m.rescueGoal;card.append(line);}}};
// Called after checkpoint handlers are installed; restarts keep exercise identity.
function bindExerciseRecovery(){const restart=(saved=false)=>{const e=saved?checkpointData.run?.snapshot.expedition?.exercise:exerciseContext(),n=saved?checkpointData.run?.snapshot.values.level:level;if(e){exerciseRequest={...e};if(saved)chosenMachine=checkpointData.run.snapshot.machine;}start(n||level,true);};$('restart').onclick=()=>restart();$('retry').onclick=()=>restart();$('restartSavedRun').onclick=()=>restart(true);const originalRecovery=showRecovery;showRecovery=function(){originalRecovery();const e=checkpointData.run?.snapshot.expedition?.exercise;if(e)$('recoveryDetail').textContent=EXERCISES[e.id].name+' · '+exerciseName(e.gear)+' · 部隊 '+checkpointData.run.snapshot.values.army+'人';};const oldHome=home;home=function(){tacticsPanel.classList.add('hidden');tacticsResultPanel.classList.add('hidden');oldHome();};$('home').onclick=home;$('pauseHome').onclick=home;if(checkpointData.run?.snapshot.expedition?.exercise&&!recovery.classList.contains('hidden'))showRecovery();}
function validTacticsProfile(c){const count=v=>Number.isInteger(v)&&v>=0&&v<=3;if(c.objectives&&(!Object.entries(c.objectives).every(([n,r])=>['7','8','9'].includes(n)&&r&&count(r.relays)&&count(r.rescued))))return false;if(!c.tactics)return true;const t=c.tactics;if(typeof t.commemorative!=='boolean'||!t.records||!Object.entries(t.records).every(([id,r])=>EXERCISES[id]&&r&&typeof r.medal==='boolean'&&Number.isInteger(r.attempts)&&r.attempts>0&&r.loadouts&&Object.entries(r.loadouts).every(([key,l])=>l&&Number.isInteger(l.attempts)&&l.attempts>0&&[l.best,l.last].every(x=>x&&MACHINES.some(m=>m.id===x.machine)&&['prism','guardian','none'].includes(x.gear)&&key===x.machine+'_'+x.gear&&typeof x.win==='boolean'&&typeof x.achieved==='boolean'&&['relays','rescued','kills','total','damage','army','score','time'].every(n=>Number.isFinite(x[n])&&x[n]>=0)&&x.total>0))))return false;return !t.commemorative||Object.keys(EXERCISES).every(id=>t.records[id]?.medal);}
function validExerciseSnapshot(e,n){return !e||EXERCISES[e.id]&&EXERCISES[e.id].level===n&&['prism','guardian','none'].includes(e.gear)&&e.version===1;}
refreshCampaign();renderHangar();
