import fs from 'node:fs';import path from 'node:path';import{createHash}from'node:crypto';import{build}from'esbuild';
const manifest=JSON.parse(fs.readFileSync('native/approved-web.json'));
for(const f of manifest.files){const p='baseline/'+f.path,b=fs.readFileSync(p);if(createHash('sha256').update(b).digest('hex')!==f.sha256)throw Error('Baseline changed: '+p);const dst='www/'+f.path;fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(p,dst);}
function transform(file,changes){let s=fs.readFileSync('www/'+file,'utf8');for(const [a,b]of changes){if(!s.includes(a))throw Error('Missing anchor '+a);s=s.replace(a,b);}fs.writeFileSync('www/'+file,s);}
transform('progression.js',[["const work=()=>{","const work=async()=>{"],["this.storage.setItem(PROFILE_KEY,JSON.stringify(p));this.profile=p;","this.storage.setItem(PROFILE_KEY,JSON.stringify(p));await this.storage.flush?.();this.profile=p;"]]);
transform('campaign.js',[["new ProfileStore(localStorage)","new ProfileStore(window.BucchibiStorage)"],["if(win)mode='settling';","if(win)mode='settling';"],["mode='ending';run.ending=0;","mode=window.BucchibiInactive?'paused':'ending';run.ending=0;"],["store.saveCheckpoint(cp,run.kind==='legacy').then","return store.saveCheckpoint(cp,run.kind==='legacy').then"]]);
fs.appendFileSync('www/campaign.js',`\nwindow.BucchibiLifecycle={background(){pause();battleAudio.ctx?.suspend().catch(()=>{});void store.queue.then(()=>window.BucchibiStorage.flush?.()).catch(storageFailure);},foreground(){clock.getDelta();dispatchEvent(new Event('resize'));if(mode==='paused')pausePanel('中断した位置から再開');}};\n`);
// Bundle JS and Capacitor bridge imports locally, including Three.js. No import-map dependency.
await build({absWorkingDir:process.cwd(),tsconfigRaw:{compilerOptions:{}},entryPoints:['./adapter/entry.mjs'],bundle:true,format:'esm',target:'safari16',alias:{three:path.resolve('www/vendor/three.module.js')},outfile:'www/native-entry.js',legalComments:'eof'});
transform('index.html',[[`<script type="module" src="campaign.js"></script>`,`<script type="module" src="native-entry.js"></script>`],[`<link rel="stylesheet" href="campaign.css">`,`<link rel="stylesheet" href="campaign.css"><link rel="stylesheet" href="native-shell.css">`]]);
fs.copyFileSync('native/shell.css','www/native-shell.css');
const files=fs.readdirSync('www',{recursive:true}).filter(f=>fs.statSync('www/'+f).isFile()).map(f=>({path:f.replaceAll('\\','/'),sha256:createHash('sha256').update(fs.readFileSync('www/'+f)).digest('hex')}));fs.mkdirSync('evidence',{recursive:true});fs.writeFileSync('evidence/offline-manifest.json',JSON.stringify({publicCommit:manifest.commit,files},null,2));console.log('Offline iOS payload prepared. No Xcode build, signing or upload.');
