export const PROFILE_KEY='bucchibi-campaign-v2',OLD_KEY='breach-run-amplify-prototype-v1',EARLY_KEY='breach-run-3d-playtest-v1',BACKUP_KEY='bucchibi-backup-before-v2';
export const SKINS=[{id:'standard',name:'ブルー隊',price:0,body:'#148edc',helmet:'#67c8ee',flag:'#42baf5',description:'頼れる基本セット。全作戦で性能は同じ。'},{id:'aurora',name:'極光隊',price:300,body:'#2cb5d9',helmet:'#d3fbff',flag:'#72ead9',description:'氷色のヘルメットと、極光の隊旗。'},{id:'deepsea',name:'深海隊',price:500,body:'#276cb4',helmet:'#98bddc',flag:'#879cff',description:'濃いブルーの制服に、銀青のヘルメット。'},{id:'starlight',name:'星巡り隊',price:null,body:'#428ddd',helmet:'#d9e8ff',flag:'#d9e8ff',description:'ログイン累計7回の記念セット。欠席しても進みは戻らない。'}];
export const utcDay=(now=Date.now())=>new Date(now).toISOString().slice(0,10);
const num=n=>Number.isFinite(n)&&n>=0?Math.floor(n):0;
export function blank(){return{version:2,revision:0,coins:0,records:{},ledger:[],owned:['standard'],equipped:'standard',badges:[],audio:{bgm:1,se:1,bgmMuted:false,seMuted:false},login:{count:0,days:[]},daily:{},checkpoint:null,legacyCheckpoint:null,legacyRecords:{},migration:null};}
export function migrate(storage){const raw=storage.getItem(PROFILE_KEY);if(raw!==null){let p;try{p=JSON.parse(raw)}catch{throw Error('保存データを読み取れません。元データは保持しています。')}if(p.version!==2)throw Error('この保存版にはまだ対応していません。元データは保持しています。');return p;}const oldRaw=storage.getItem(OLD_KEY),earlyRaw=storage.getItem(EARLY_KEY),source=oldRaw!==null?OLD_KEY:EARLY_KEY,text=oldRaw??earlyRaw;let old;if(text!==null){try{old=JSON.parse(text)}catch{throw Error('旧保存データが壊れています。上書きせず保持しました。')}if(old.version!==1)throw Error('旧保存版を確認できません。上書きせず保持しました。');}const p=blank();if(old){if(storage.getItem(BACKUP_KEY)===null)storage.setItem(BACKUP_KEY,JSON.stringify({source,oldRaw,earlyRaw,createdAt:new Date().toISOString()}));p.coins=num(old.alloy);p.legacyRecords=structuredClone(old.records||{});p.ledger=[...new Set((old.ledger||[]).filter(x=>typeof x==='string'))];if(old.paintOwned)p.owned.push('aurora');if(old.paintOwned&&old.paint)p.equipped='aurora';p.badges=[2,5,9].filter(i=>old.records?.[i]).map(i=>'legacy-'+i);p.legacyCheckpoint=old.checkpoint?structuredClone(old.checkpoint):null;if(old.sound===false)p.audio.bgmMuted=p.audio.seMuted=true;p.migration={source,acknowledged:false,oldClears:Object.keys(old.records||{}).length,balance:p.coins};}storage.setItem(PROFILE_KEY,JSON.stringify(p));return p;}
export function applyReward(p,id,amount,details={}){if(p.ledger.includes(id))return false;if(!Number.isSafeInteger(amount)||amount<0)throw Error('Invalid reward');p.coins+=amount;p.ledger.push(id);p.lastReward={id,amount,...details};return true;}
export function complete(p,run){const transaction='run:'+run.id;if(p.ledger.includes(transaction))return run.receipt||{earned:0,first:false,total:p.coins};let earned=0,first=false,bonus=0;if(run.kind==='legacy'){if(p.ledger.includes(run.id)||run.receipt){p.ledger.push(transaction);return run.receipt||{earned:0,first:false,total:p.coins};}first=!p.legacyRecords[run.stage];earned=first?20+run.stage*3:3;p.legacyRecords[run.stage]={clears:(p.legacyRecords[run.stage]?.clears||0)+1,best:run.force};p.ledger.push(run.id);}else if(run.kind==='daily'){const record=p.daily[run.dailyDay]||(p.daily[run.dailyDay]={done:[],bonus:false});first=!record.done.includes(run.dailySlot);if(first){record.done.push(run.dailySlot);earned=25;}if(record.done.length===3&&!record.bonus){record.bonus=true;bonus=25;earned+=bonus;}}else{const id=run.spec.id;first=!p.records[id];earned=first?100:20;if(first&&run.spec.milestone){earned+=100;bonus=100;}p.records[id]={clears:(p.records[id]?.clears||0)+1,best:Math.max(p.records[id]?.best||0,run.force)};if(first&&[10,60,100].includes(run.stage+1)){const badge='campaign-'+(run.stage+1);if(!p.badges.includes(badge))p.badges.push(badge);}}applyReward(p,transaction,earned,{kind:run.kind||'campaign'});return{earned,first,bonus,total:p.coins,id:run.id};}
export function buy(p,id){const item=SKINS.find(x=>x.id===id);if(!item)throw Error('外観が見つかりません');if(p.owned.includes(id)){p.equipped=id;return{purchased:false};}if(item.price===null)throw Error('ログイン累計7回で獲得できます');if(p.coins<item.price)throw Error('コインが足りません');p.coins-=item.price;p.owned.push(id);p.equipped=id;p.ledger.push('buy:'+id);return{purchased:true};}
export function claimLogin(p,day){if(p.login.days.includes(day)||day<(p.login.lastDay||''))return{claimed:false,amount:0};const slot=p.login.count%7;let amount=[20,20,25,25,30,30,0][slot],skin=false;if(slot===6){if(p.owned.includes('starlight'))amount=60;else{p.owned.push('starlight');skin=true;}}p.login.count++;p.login.days.push(day);p.login.lastDay=day;applyReward(p,'login:'+day,amount);return{claimed:true,amount,skin,slot:slot+1};}
export function nextStage(p,stages){const i=stages.findIndex(s=>!p.records[s.id]);return i<0?stages.length-1:i;}
export function unlocked(p,index,stages){return index===0||!!p.records[stages[index].id]||!!p.records[stages[index-1]?.id];}
export function dailyUnlocked(p){return !!p.records.c010;}
export class ProfileStore{constructor(storage){this.storage=storage;this.profile=migrate(storage);this.queue=Promise.resolve();}read(){const p=JSON.parse(this.storage.getItem(PROFILE_KEY));if(p?.version!==2)throw Error('保存版が一致しません');return p;}transaction(fn){const work=()=>{const p=this.read(),result=fn(p);p.revision=(p.revision||0)+1;this.storage.setItem(PROFILE_KEY,JSON.stringify(p));this.profile=p;return{profile:p,result};};const execute=()=>globalThis.navigator?.locks?navigator.locks.request(PROFILE_KEY,work):work();const job=this.queue.then(execute);this.queue=job.catch(()=>{});return job;}saveCheckpoint(cp,legacy=false){return this.transaction(p=>{p[legacy?'legacyCheckpoint':'checkpoint']=cp;});}}
